-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity kyber_mult_fwd_stage2_t_32_s_p_ZL6FWD_MW_0_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 16; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of kyber_mult_fwd_stage2_t_32_s_p_ZL6FWD_MW_0_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1100101100101011", 1 => "1100101100101011", 2 => "1100101100101011", 3 => "1100101100101011", 
    4 => "1100101100101011", 5 => "1100101100101011", 6 => "1100101100101011", 7 => "1100101100101011", 
    8 => "0011000001110010", 9 => "0011000001110010", 10 => "0011000001110010", 11 => "0011000001110010", 
    12 => "0011000001110010", 13 => "0011000001110010", 14 => "0011000001110010", 15 => "0011000001110010", 
    16 => "1001000111100001", 17 => "1001000111100001", 18 => "1001000111100001", 19 => "1001000111100001", 
    20 => "1001000111100001", 21 => "1001000111100001", 22 => "1001000111100001", 23 => "1001000111100001", 
    24 => "0100000100110110", 25 => "0100000100110110", 26 => "0100000100110110", 27 => "0100000100110110", 
    28 => "0100000100110110", 29 => "0100000100110110", 30 => "0100000100110110", 31 => "0100000100110110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

