// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module kyber_mult_fwd_all_Pipeline_FW_RD (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sA0_dout,
        sA0_num_data_valid,
        sA0_fifo_cap,
        sA0_empty_n,
        sA0_read,
        sB0_dout,
        sB0_num_data_valid,
        sB0_fifo_cap,
        sB0_empty_n,
        sB0_read,
        B_15_address0,
        B_15_ce0,
        B_15_we0,
        B_15_d0,
        B_14_address0,
        B_14_ce0,
        B_14_we0,
        B_14_d0,
        B_13_address0,
        B_13_ce0,
        B_13_we0,
        B_13_d0,
        B_12_address0,
        B_12_ce0,
        B_12_we0,
        B_12_d0,
        B_11_address0,
        B_11_ce0,
        B_11_we0,
        B_11_d0,
        B_10_address0,
        B_10_ce0,
        B_10_we0,
        B_10_d0,
        B_9_address0,
        B_9_ce0,
        B_9_we0,
        B_9_d0,
        B_8_address0,
        B_8_ce0,
        B_8_we0,
        B_8_d0,
        B_7_address0,
        B_7_ce0,
        B_7_we0,
        B_7_d0,
        B_6_address0,
        B_6_ce0,
        B_6_we0,
        B_6_d0,
        B_5_address0,
        B_5_ce0,
        B_5_we0,
        B_5_d0,
        B_4_address0,
        B_4_ce0,
        B_4_we0,
        B_4_d0,
        B_3_address0,
        B_3_ce0,
        B_3_we0,
        B_3_d0,
        B_2_address0,
        B_2_ce0,
        B_2_we0,
        B_2_d0,
        B_1_address0,
        B_1_ce0,
        B_1_we0,
        B_1_d0,
        B_address0,
        B_ce0,
        B_we0,
        B_d0,
        A_15_address0,
        A_15_ce0,
        A_15_we0,
        A_15_d0,
        A_14_address0,
        A_14_ce0,
        A_14_we0,
        A_14_d0,
        A_13_address0,
        A_13_ce0,
        A_13_we0,
        A_13_d0,
        A_12_address0,
        A_12_ce0,
        A_12_we0,
        A_12_d0,
        A_11_address0,
        A_11_ce0,
        A_11_we0,
        A_11_d0,
        A_10_address0,
        A_10_ce0,
        A_10_we0,
        A_10_d0,
        A_9_address0,
        A_9_ce0,
        A_9_we0,
        A_9_d0,
        A_8_address0,
        A_8_ce0,
        A_8_we0,
        A_8_d0,
        A_7_address0,
        A_7_ce0,
        A_7_we0,
        A_7_d0,
        A_6_address0,
        A_6_ce0,
        A_6_we0,
        A_6_d0,
        A_5_address0,
        A_5_ce0,
        A_5_we0,
        A_5_d0,
        A_4_address0,
        A_4_ce0,
        A_4_we0,
        A_4_d0,
        A_3_address0,
        A_3_ce0,
        A_3_we0,
        A_3_d0,
        A_2_address0,
        A_2_ce0,
        A_2_we0,
        A_2_d0,
        A_1_address0,
        A_1_ce0,
        A_1_we0,
        A_1_d0,
        A_address0,
        A_ce0,
        A_we0,
        A_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [191:0] sA0_dout;
input  [5:0] sA0_num_data_valid;
input  [5:0] sA0_fifo_cap;
input   sA0_empty_n;
output   sA0_read;
input  [191:0] sB0_dout;
input  [5:0] sB0_num_data_valid;
input  [5:0] sB0_fifo_cap;
input   sB0_empty_n;
output   sB0_read;
output  [3:0] B_15_address0;
output   B_15_ce0;
output   B_15_we0;
output  [11:0] B_15_d0;
output  [3:0] B_14_address0;
output   B_14_ce0;
output   B_14_we0;
output  [11:0] B_14_d0;
output  [3:0] B_13_address0;
output   B_13_ce0;
output   B_13_we0;
output  [11:0] B_13_d0;
output  [3:0] B_12_address0;
output   B_12_ce0;
output   B_12_we0;
output  [11:0] B_12_d0;
output  [3:0] B_11_address0;
output   B_11_ce0;
output   B_11_we0;
output  [11:0] B_11_d0;
output  [3:0] B_10_address0;
output   B_10_ce0;
output   B_10_we0;
output  [11:0] B_10_d0;
output  [3:0] B_9_address0;
output   B_9_ce0;
output   B_9_we0;
output  [11:0] B_9_d0;
output  [3:0] B_8_address0;
output   B_8_ce0;
output   B_8_we0;
output  [11:0] B_8_d0;
output  [3:0] B_7_address0;
output   B_7_ce0;
output   B_7_we0;
output  [11:0] B_7_d0;
output  [3:0] B_6_address0;
output   B_6_ce0;
output   B_6_we0;
output  [11:0] B_6_d0;
output  [3:0] B_5_address0;
output   B_5_ce0;
output   B_5_we0;
output  [11:0] B_5_d0;
output  [3:0] B_4_address0;
output   B_4_ce0;
output   B_4_we0;
output  [11:0] B_4_d0;
output  [3:0] B_3_address0;
output   B_3_ce0;
output   B_3_we0;
output  [11:0] B_3_d0;
output  [3:0] B_2_address0;
output   B_2_ce0;
output   B_2_we0;
output  [11:0] B_2_d0;
output  [3:0] B_1_address0;
output   B_1_ce0;
output   B_1_we0;
output  [11:0] B_1_d0;
output  [3:0] B_address0;
output   B_ce0;
output   B_we0;
output  [11:0] B_d0;
output  [3:0] A_15_address0;
output   A_15_ce0;
output   A_15_we0;
output  [11:0] A_15_d0;
output  [3:0] A_14_address0;
output   A_14_ce0;
output   A_14_we0;
output  [11:0] A_14_d0;
output  [3:0] A_13_address0;
output   A_13_ce0;
output   A_13_we0;
output  [11:0] A_13_d0;
output  [3:0] A_12_address0;
output   A_12_ce0;
output   A_12_we0;
output  [11:0] A_12_d0;
output  [3:0] A_11_address0;
output   A_11_ce0;
output   A_11_we0;
output  [11:0] A_11_d0;
output  [3:0] A_10_address0;
output   A_10_ce0;
output   A_10_we0;
output  [11:0] A_10_d0;
output  [3:0] A_9_address0;
output   A_9_ce0;
output   A_9_we0;
output  [11:0] A_9_d0;
output  [3:0] A_8_address0;
output   A_8_ce0;
output   A_8_we0;
output  [11:0] A_8_d0;
output  [3:0] A_7_address0;
output   A_7_ce0;
output   A_7_we0;
output  [11:0] A_7_d0;
output  [3:0] A_6_address0;
output   A_6_ce0;
output   A_6_we0;
output  [11:0] A_6_d0;
output  [3:0] A_5_address0;
output   A_5_ce0;
output   A_5_we0;
output  [11:0] A_5_d0;
output  [3:0] A_4_address0;
output   A_4_ce0;
output   A_4_we0;
output  [11:0] A_4_d0;
output  [3:0] A_3_address0;
output   A_3_ce0;
output   A_3_we0;
output  [11:0] A_3_d0;
output  [3:0] A_2_address0;
output   A_2_ce0;
output   A_2_we0;
output  [11:0] A_2_d0;
output  [3:0] A_1_address0;
output   A_1_ce0;
output   A_1_we0;
output  [11:0] A_1_d0;
output  [3:0] A_address0;
output   A_ce0;
output   A_we0;
output  [11:0] A_d0;

reg ap_idle;
reg sA0_read;
reg sB0_read;
reg B_15_ce0;
reg B_15_we0;
reg B_14_ce0;
reg B_14_we0;
reg B_13_ce0;
reg B_13_we0;
reg B_12_ce0;
reg B_12_we0;
reg B_11_ce0;
reg B_11_we0;
reg B_10_ce0;
reg B_10_we0;
reg B_9_ce0;
reg B_9_we0;
reg B_8_ce0;
reg B_8_we0;
reg B_7_ce0;
reg B_7_we0;
reg B_6_ce0;
reg B_6_we0;
reg B_5_ce0;
reg B_5_we0;
reg B_4_ce0;
reg B_4_we0;
reg B_3_ce0;
reg B_3_we0;
reg B_2_ce0;
reg B_2_we0;
reg B_1_ce0;
reg B_1_we0;
reg B_ce0;
reg B_we0;
reg A_15_ce0;
reg A_15_we0;
reg A_14_ce0;
reg A_14_we0;
reg A_13_ce0;
reg A_13_we0;
reg A_12_ce0;
reg A_12_we0;
reg A_11_ce0;
reg A_11_we0;
reg A_10_ce0;
reg A_10_we0;
reg A_9_ce0;
reg A_9_we0;
reg A_8_ce0;
reg A_8_we0;
reg A_7_ce0;
reg A_7_we0;
reg A_6_ce0;
reg A_6_we0;
reg A_5_ce0;
reg A_5_we0;
reg A_4_ce0;
reg A_4_we0;
reg A_3_ce0;
reg A_3_we0;
reg A_2_ce0;
reg A_2_we0;
reg A_1_ce0;
reg A_1_we0;
reg A_ce0;
reg A_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln187_fu_602_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    sA0_blk_n;
wire    ap_block_pp0_stage0;
reg    sB0_blk_n;
reg   [4:0] w_58_reg_1001;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln187_fu_619_p1;
reg   [4:0] w_fu_162;
wire   [4:0] add_ln187_fu_608_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_w_58;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 w_fu_162 = 5'd0;
#0 ap_done_reg = 1'b0;
end

kyber_mult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln187_fu_602_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            w_fu_162 <= add_ln187_fu_608_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            w_fu_162 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_58_reg_1001 <= ap_sig_allocacmp_w_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_10_ce0 = 1'b1;
    end else begin
        A_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_10_we0 = 1'b1;
    end else begin
        A_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_11_ce0 = 1'b1;
    end else begin
        A_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_11_we0 = 1'b1;
    end else begin
        A_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_12_ce0 = 1'b1;
    end else begin
        A_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_12_we0 = 1'b1;
    end else begin
        A_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_13_ce0 = 1'b1;
    end else begin
        A_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_13_we0 = 1'b1;
    end else begin
        A_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_14_ce0 = 1'b1;
    end else begin
        A_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_14_we0 = 1'b1;
    end else begin
        A_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_15_ce0 = 1'b1;
    end else begin
        A_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_15_we0 = 1'b1;
    end else begin
        A_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_1_ce0 = 1'b1;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_1_we0 = 1'b1;
    end else begin
        A_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_2_ce0 = 1'b1;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_2_we0 = 1'b1;
    end else begin
        A_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_3_ce0 = 1'b1;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_3_we0 = 1'b1;
    end else begin
        A_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_4_ce0 = 1'b1;
    end else begin
        A_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_4_we0 = 1'b1;
    end else begin
        A_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_5_ce0 = 1'b1;
    end else begin
        A_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_5_we0 = 1'b1;
    end else begin
        A_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_6_ce0 = 1'b1;
    end else begin
        A_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_6_we0 = 1'b1;
    end else begin
        A_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_7_ce0 = 1'b1;
    end else begin
        A_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_7_we0 = 1'b1;
    end else begin
        A_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_8_ce0 = 1'b1;
    end else begin
        A_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_8_we0 = 1'b1;
    end else begin
        A_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_9_ce0 = 1'b1;
    end else begin
        A_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_9_we0 = 1'b1;
    end else begin
        A_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_we0 = 1'b1;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_10_ce0 = 1'b1;
    end else begin
        B_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_10_we0 = 1'b1;
    end else begin
        B_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_11_ce0 = 1'b1;
    end else begin
        B_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_11_we0 = 1'b1;
    end else begin
        B_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_12_ce0 = 1'b1;
    end else begin
        B_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_12_we0 = 1'b1;
    end else begin
        B_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_13_ce0 = 1'b1;
    end else begin
        B_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_13_we0 = 1'b1;
    end else begin
        B_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_14_ce0 = 1'b1;
    end else begin
        B_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_14_we0 = 1'b1;
    end else begin
        B_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_15_ce0 = 1'b1;
    end else begin
        B_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_15_we0 = 1'b1;
    end else begin
        B_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_1_ce0 = 1'b1;
    end else begin
        B_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_1_we0 = 1'b1;
    end else begin
        B_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_2_ce0 = 1'b1;
    end else begin
        B_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_2_we0 = 1'b1;
    end else begin
        B_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_3_ce0 = 1'b1;
    end else begin
        B_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_3_we0 = 1'b1;
    end else begin
        B_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_4_ce0 = 1'b1;
    end else begin
        B_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_4_we0 = 1'b1;
    end else begin
        B_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_5_ce0 = 1'b1;
    end else begin
        B_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_5_we0 = 1'b1;
    end else begin
        B_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_6_ce0 = 1'b1;
    end else begin
        B_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_6_we0 = 1'b1;
    end else begin
        B_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_7_ce0 = 1'b1;
    end else begin
        B_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_7_we0 = 1'b1;
    end else begin
        B_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_8_ce0 = 1'b1;
    end else begin
        B_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_8_we0 = 1'b1;
    end else begin
        B_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_9_ce0 = 1'b1;
    end else begin
        B_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_9_we0 = 1'b1;
    end else begin
        B_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_ce0 = 1'b1;
    end else begin
        B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_we0 = 1'b1;
    end else begin
        B_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln187_fu_602_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_w_58 = 5'd0;
    end else begin
        ap_sig_allocacmp_w_58 = w_fu_162;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sA0_blk_n = sA0_empty_n;
    end else begin
        sA0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sA0_read = 1'b1;
    end else begin
        sA0_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sB0_blk_n = sB0_empty_n;
    end else begin
        sB0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sB0_read = 1'b1;
    end else begin
        sB0_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_10_address0 = zext_ln187_fu_619_p1;

assign A_10_d0 = {{sA0_dout[131:120]}};

assign A_11_address0 = zext_ln187_fu_619_p1;

assign A_11_d0 = {{sA0_dout[143:132]}};

assign A_12_address0 = zext_ln187_fu_619_p1;

assign A_12_d0 = {{sA0_dout[155:144]}};

assign A_13_address0 = zext_ln187_fu_619_p1;

assign A_13_d0 = {{sA0_dout[167:156]}};

assign A_14_address0 = zext_ln187_fu_619_p1;

assign A_14_d0 = {{sA0_dout[179:168]}};

assign A_15_address0 = zext_ln187_fu_619_p1;

assign A_15_d0 = {{sA0_dout[191:180]}};

assign A_1_address0 = zext_ln187_fu_619_p1;

assign A_1_d0 = {{sA0_dout[23:12]}};

assign A_2_address0 = zext_ln187_fu_619_p1;

assign A_2_d0 = {{sA0_dout[35:24]}};

assign A_3_address0 = zext_ln187_fu_619_p1;

assign A_3_d0 = {{sA0_dout[47:36]}};

assign A_4_address0 = zext_ln187_fu_619_p1;

assign A_4_d0 = {{sA0_dout[59:48]}};

assign A_5_address0 = zext_ln187_fu_619_p1;

assign A_5_d0 = {{sA0_dout[71:60]}};

assign A_6_address0 = zext_ln187_fu_619_p1;

assign A_6_d0 = {{sA0_dout[83:72]}};

assign A_7_address0 = zext_ln187_fu_619_p1;

assign A_7_d0 = {{sA0_dout[95:84]}};

assign A_8_address0 = zext_ln187_fu_619_p1;

assign A_8_d0 = {{sA0_dout[107:96]}};

assign A_9_address0 = zext_ln187_fu_619_p1;

assign A_9_d0 = {{sA0_dout[119:108]}};

assign A_address0 = zext_ln187_fu_619_p1;

assign A_d0 = sA0_dout[11:0];

assign B_10_address0 = zext_ln187_fu_619_p1;

assign B_10_d0 = {{sB0_dout[131:120]}};

assign B_11_address0 = zext_ln187_fu_619_p1;

assign B_11_d0 = {{sB0_dout[143:132]}};

assign B_12_address0 = zext_ln187_fu_619_p1;

assign B_12_d0 = {{sB0_dout[155:144]}};

assign B_13_address0 = zext_ln187_fu_619_p1;

assign B_13_d0 = {{sB0_dout[167:156]}};

assign B_14_address0 = zext_ln187_fu_619_p1;

assign B_14_d0 = {{sB0_dout[179:168]}};

assign B_15_address0 = zext_ln187_fu_619_p1;

assign B_15_d0 = {{sB0_dout[191:180]}};

assign B_1_address0 = zext_ln187_fu_619_p1;

assign B_1_d0 = {{sB0_dout[23:12]}};

assign B_2_address0 = zext_ln187_fu_619_p1;

assign B_2_d0 = {{sB0_dout[35:24]}};

assign B_3_address0 = zext_ln187_fu_619_p1;

assign B_3_d0 = {{sB0_dout[47:36]}};

assign B_4_address0 = zext_ln187_fu_619_p1;

assign B_4_d0 = {{sB0_dout[59:48]}};

assign B_5_address0 = zext_ln187_fu_619_p1;

assign B_5_d0 = {{sB0_dout[71:60]}};

assign B_6_address0 = zext_ln187_fu_619_p1;

assign B_6_d0 = {{sB0_dout[83:72]}};

assign B_7_address0 = zext_ln187_fu_619_p1;

assign B_7_d0 = {{sB0_dout[95:84]}};

assign B_8_address0 = zext_ln187_fu_619_p1;

assign B_8_d0 = {{sB0_dout[107:96]}};

assign B_9_address0 = zext_ln187_fu_619_p1;

assign B_9_d0 = {{sB0_dout[119:108]}};

assign B_address0 = zext_ln187_fu_619_p1;

assign B_d0 = sB0_dout[11:0];

assign add_ln187_fu_608_p2 = (ap_sig_allocacmp_w_58 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((sB0_empty_n == 1'b0) | (sA0_empty_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln187_fu_602_p2 = ((ap_sig_allocacmp_w_58 == 5'd16) ? 1'b1 : 1'b0);

assign zext_ln187_fu_619_p1 = w_58_reg_1001;

endmodule //kyber_mult_fwd_all_Pipeline_FW_RD
