

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.local_x_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263",
		"DependenceCheck" : [
			{"FromInitialState" : "ap_enable_state1_pp0_iter0_stage0", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_36", "FromInitialSV" : "0", "FromFinalState" : "ap_enable_state2_pp0_iter0_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_40", "FromFinalSV" : "1", "FromAddress" : "local_x_address1", "FromType" : "R", "ToInitialState" : "ap_enable_state6_pp0_iter1_stage2", "ToInitialIteration" : "ap_enable_reg_pp0_iter1", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter2", "ToInitialOperation" : "ap_enable_operation_63", "ToInitialSV" : "5", "ToFinalState" : "ap_enable_state6_pp0_iter1_stage2", "ToFinalIteration" : "ap_enable_reg_pp0_iter1", "ToFinalOperation" : "ap_enable_operation_63", "ToFinalSV" : "5", "ToAddress" : "local_x_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state1_pp0_iter0_stage0", "FromInitialIteration" : "ap_enable_reg_pp0_iter0", "FromInitialOperation" : "ap_enable_operation_36", "FromInitialSV" : "0", "FromFinalState" : "ap_enable_state2_pp0_iter0_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter0", "FromFinalOperation" : "ap_enable_operation_40", "FromFinalSV" : "1", "FromAddress" : "local_x_address1", "FromType" : "R", "ToInitialState" : "ap_enable_state8_pp0_iter2_stage1", "ToInitialIteration" : "ap_enable_reg_pp0_iter2", "ToInitialNextIteration" : "null", "ToInitialOperation" : "ap_enable_operation_71", "ToInitialSV" : "7", "ToFinalState" : "ap_enable_state8_pp0_iter2_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter2", "ToFinalOperation" : "ap_enable_operation_71", "ToFinalSV" : "7", "ToAddress" : "local_x_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state4_pp0_iter1_stage0", "FromInitialIteration" : "ap_enable_reg_pp0_iter1", "FromInitialOperation" : "ap_enable_operation_47", "FromInitialSV" : "3", "FromFinalState" : "ap_enable_state5_pp0_iter1_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter1", "FromFinalOperation" : "ap_enable_operation_49", "FromFinalSV" : "4", "FromAddress" : "local_x_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state6_pp0_iter1_stage2", "ToInitialIteration" : "ap_enable_reg_pp0_iter1", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter2", "ToInitialOperation" : "ap_enable_operation_63", "ToInitialSV" : "5", "ToFinalState" : "ap_enable_state6_pp0_iter1_stage2", "ToFinalIteration" : "ap_enable_reg_pp0_iter1", "ToFinalOperation" : "ap_enable_operation_63", "ToFinalSV" : "5", "ToAddress" : "local_x_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state4_pp0_iter1_stage0", "FromInitialIteration" : "ap_enable_reg_pp0_iter1", "FromInitialOperation" : "ap_enable_operation_47", "FromInitialSV" : "3", "FromFinalState" : "ap_enable_state5_pp0_iter1_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter1", "FromFinalOperation" : "ap_enable_operation_49", "FromFinalSV" : "4", "FromAddress" : "local_x_address0", "FromType" : "R", "ToInitialState" : "ap_enable_state8_pp0_iter2_stage1", "ToInitialIteration" : "ap_enable_reg_pp0_iter2", "ToInitialNextIteration" : "null", "ToInitialOperation" : "ap_enable_operation_71", "ToInitialSV" : "7", "ToFinalState" : "ap_enable_state8_pp0_iter2_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter2", "ToFinalOperation" : "ap_enable_operation_71", "ToFinalSV" : "7", "ToAddress" : "local_x_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "WAR"},
			{"FromInitialState" : "ap_enable_state6_pp0_iter1_stage2", "FromInitialIteration" : "ap_enable_reg_pp0_iter1", "FromInitialOperation" : "ap_enable_operation_63", "FromInitialSV" : "5", "FromFinalState" : "ap_enable_state6_pp0_iter1_stage2", "FromFinalIteration" : "ap_enable_reg_pp0_iter1", "FromFinalOperation" : "ap_enable_operation_63", "FromFinalSV" : "5", "FromAddress" : "local_x_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state1_pp0_iter0_stage0", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_36", "ToInitialSV" : "0", "ToFinalState" : "ap_enable_state2_pp0_iter0_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_40", "ToFinalSV" : "1", "ToAddress" : "local_x_address1", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state1_pp0_iter0_stage0", "ap_enable_state4_pp0_iter1_stage0"]},
			{"FromInitialState" : "ap_enable_state6_pp0_iter1_stage2", "FromInitialIteration" : "ap_enable_reg_pp0_iter1", "FromInitialOperation" : "ap_enable_operation_63", "FromInitialSV" : "5", "FromFinalState" : "ap_enable_state6_pp0_iter1_stage2", "FromFinalIteration" : "ap_enable_reg_pp0_iter1", "FromFinalOperation" : "ap_enable_operation_63", "FromFinalSV" : "5", "FromAddress" : "local_x_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state4_pp0_iter1_stage0", "ToInitialIteration" : "ap_enable_reg_pp0_iter1", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter2", "ToInitialOperation" : "ap_enable_operation_47", "ToInitialSV" : "3", "ToFinalState" : "ap_enable_state5_pp0_iter1_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter1", "ToFinalOperation" : "ap_enable_operation_49", "ToFinalSV" : "4", "ToAddress" : "local_x_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state4_pp0_iter1_stage0"]},
			{"FromInitialState" : "ap_enable_state6_pp0_iter1_stage2", "FromInitialIteration" : "ap_enable_reg_pp0_iter1", "FromInitialOperation" : "ap_enable_operation_63", "FromInitialSV" : "5", "FromFinalState" : "ap_enable_state6_pp0_iter1_stage2", "FromFinalIteration" : "ap_enable_reg_pp0_iter1", "FromFinalOperation" : "ap_enable_operation_63", "FromFinalSV" : "5", "FromAddress" : "local_x_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state8_pp0_iter2_stage1", "ToInitialIteration" : "ap_enable_reg_pp0_iter2", "ToInitialNextIteration" : "null", "ToInitialOperation" : "ap_enable_operation_71", "ToInitialSV" : "7", "ToFinalState" : "ap_enable_state8_pp0_iter2_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter2", "ToFinalOperation" : "ap_enable_operation_71", "ToFinalSV" : "7", "ToAddress" : "local_x_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "WAW"},
			{"FromInitialState" : "ap_enable_state8_pp0_iter2_stage1", "FromInitialIteration" : "ap_enable_reg_pp0_iter2", "FromInitialOperation" : "ap_enable_operation_71", "FromInitialSV" : "7", "FromFinalState" : "ap_enable_state8_pp0_iter2_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter2", "FromFinalOperation" : "ap_enable_operation_71", "FromFinalSV" : "7", "FromAddress" : "local_x_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state1_pp0_iter0_stage0", "ToInitialIteration" : "ap_enable_reg_pp0_iter0", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter1", "ToInitialOperation" : "ap_enable_operation_36", "ToInitialSV" : "0", "ToFinalState" : "ap_enable_state2_pp0_iter0_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter0", "ToFinalOperation" : "ap_enable_operation_40", "ToFinalSV" : "1", "ToAddress" : "local_x_address1", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state1_pp0_iter0_stage0", "ap_enable_state4_pp0_iter1_stage0"]},
			{"FromInitialState" : "ap_enable_state8_pp0_iter2_stage1", "FromInitialIteration" : "ap_enable_reg_pp0_iter2", "FromInitialOperation" : "ap_enable_operation_71", "FromInitialSV" : "7", "FromFinalState" : "ap_enable_state8_pp0_iter2_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter2", "FromFinalOperation" : "ap_enable_operation_71", "FromFinalSV" : "7", "FromAddress" : "local_x_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state4_pp0_iter1_stage0", "ToInitialIteration" : "ap_enable_reg_pp0_iter1", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter2", "ToInitialOperation" : "ap_enable_operation_47", "ToInitialSV" : "3", "ToFinalState" : "ap_enable_state5_pp0_iter1_stage1", "ToFinalIteration" : "ap_enable_reg_pp0_iter1", "ToFinalOperation" : "ap_enable_operation_49", "ToFinalSV" : "4", "ToAddress" : "local_x_address0", "ToType" : "R", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "RAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state4_pp0_iter1_stage0"]},
			{"FromInitialState" : "ap_enable_state8_pp0_iter2_stage1", "FromInitialIteration" : "ap_enable_reg_pp0_iter2", "FromInitialOperation" : "ap_enable_operation_71", "FromInitialSV" : "7", "FromFinalState" : "ap_enable_state8_pp0_iter2_stage1", "FromFinalIteration" : "ap_enable_reg_pp0_iter2", "FromFinalOperation" : "ap_enable_operation_71", "FromFinalSV" : "7", "FromAddress" : "local_x_address1", "FromType" : "W", "ToInitialState" : "ap_enable_state6_pp0_iter1_stage2", "ToInitialIteration" : "ap_enable_reg_pp0_iter1", "ToInitialNextIteration" : "ap_enable_reg_pp0_iter2", "ToInitialOperation" : "ap_enable_operation_63", "ToInitialSV" : "5", "ToFinalState" : "ap_enable_state6_pp0_iter1_stage2", "ToFinalIteration" : "ap_enable_reg_pp0_iter1", "ToFinalOperation" : "ap_enable_operation_63", "ToFinalSV" : "5", "ToAddress" : "local_x_address1", "ToType" : "W", "PipelineBlock" : "ap_block_pp0", "AddressWidth" : "16", "II" : "3", "Pragma" : "(hls-design/ntt-kernel.cpp:88:9)", "Type" : "WAW", "StateEnableSignalListForFifoShift" : ["ap_enable_state6_pp0_iter1_stage2"]}]},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263.mul_32ns_32ns_64_1_1_U8"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263.mul_32s_32s_32_1_1_U9"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U"}]}
set DependenceCheckSize 10
