// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module kyber_mult_inv_all_Pipeline_IN_WR (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sC1_din,
        sC1_num_data_valid,
        sC1_fifo_cap,
        sC1_full_n,
        sC1_write,
        C_address0,
        C_ce0,
        C_q0,
        C_1_address0,
        C_1_ce0,
        C_1_q0,
        C_2_address0,
        C_2_ce0,
        C_2_q0,
        C_3_address0,
        C_3_ce0,
        C_3_q0,
        C_4_address0,
        C_4_ce0,
        C_4_q0,
        C_5_address0,
        C_5_ce0,
        C_5_q0,
        C_6_address0,
        C_6_ce0,
        C_6_q0,
        C_7_address0,
        C_7_ce0,
        C_7_q0,
        C_8_address0,
        C_8_ce0,
        C_8_q0,
        C_9_address0,
        C_9_ce0,
        C_9_q0,
        C_10_address0,
        C_10_ce0,
        C_10_q0,
        C_11_address0,
        C_11_ce0,
        C_11_q0,
        C_12_address0,
        C_12_ce0,
        C_12_q0,
        C_13_address0,
        C_13_ce0,
        C_13_q0,
        C_14_address0,
        C_14_ce0,
        C_14_q0,
        C_15_address0,
        C_15_ce0,
        C_15_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [191:0] sC1_din;
input  [5:0] sC1_num_data_valid;
input  [5:0] sC1_fifo_cap;
input   sC1_full_n;
output   sC1_write;
output  [3:0] C_address0;
output   C_ce0;
input  [11:0] C_q0;
output  [3:0] C_1_address0;
output   C_1_ce0;
input  [11:0] C_1_q0;
output  [3:0] C_2_address0;
output   C_2_ce0;
input  [11:0] C_2_q0;
output  [3:0] C_3_address0;
output   C_3_ce0;
input  [11:0] C_3_q0;
output  [3:0] C_4_address0;
output   C_4_ce0;
input  [11:0] C_4_q0;
output  [3:0] C_5_address0;
output   C_5_ce0;
input  [11:0] C_5_q0;
output  [3:0] C_6_address0;
output   C_6_ce0;
input  [11:0] C_6_q0;
output  [3:0] C_7_address0;
output   C_7_ce0;
input  [11:0] C_7_q0;
output  [3:0] C_8_address0;
output   C_8_ce0;
input  [11:0] C_8_q0;
output  [3:0] C_9_address0;
output   C_9_ce0;
input  [11:0] C_9_q0;
output  [3:0] C_10_address0;
output   C_10_ce0;
input  [11:0] C_10_q0;
output  [3:0] C_11_address0;
output   C_11_ce0;
input  [11:0] C_11_q0;
output  [3:0] C_12_address0;
output   C_12_ce0;
input  [11:0] C_12_q0;
output  [3:0] C_13_address0;
output   C_13_ce0;
input  [11:0] C_13_q0;
output  [3:0] C_14_address0;
output   C_14_ce0;
input  [11:0] C_14_q0;
output  [3:0] C_15_address0;
output   C_15_ce0;
input  [11:0] C_15_q0;

reg ap_idle;
reg sC1_write;
reg C_ce0;
reg C_1_ce0;
reg C_2_ce0;
reg C_3_ce0;
reg C_4_ce0;
reg C_5_ce0;
reg C_6_ce0;
reg C_7_ce0;
reg C_8_ce0;
reg C_9_ce0;
reg C_10_ce0;
reg C_11_ce0;
reg C_12_ce0;
reg C_13_ce0;
reg C_14_ce0;
reg C_15_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln259_fu_295_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    sC1_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln259_fu_307_p1;
reg   [4:0] w_fu_68;
wire   [4:0] add_ln259_fu_301_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_w_1;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 w_fu_68 = 5'd0;
#0 ap_done_reg = 1'b0;
end

kyber_mult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln259_fu_295_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            w_fu_68 <= add_ln259_fu_301_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            w_fu_68 <= 5'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_10_ce0 = 1'b1;
    end else begin
        C_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_11_ce0 = 1'b1;
    end else begin
        C_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_12_ce0 = 1'b1;
    end else begin
        C_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_13_ce0 = 1'b1;
    end else begin
        C_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_14_ce0 = 1'b1;
    end else begin
        C_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_15_ce0 = 1'b1;
    end else begin
        C_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_1_ce0 = 1'b1;
    end else begin
        C_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_2_ce0 = 1'b1;
    end else begin
        C_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_3_ce0 = 1'b1;
    end else begin
        C_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_4_ce0 = 1'b1;
    end else begin
        C_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_5_ce0 = 1'b1;
    end else begin
        C_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_6_ce0 = 1'b1;
    end else begin
        C_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_7_ce0 = 1'b1;
    end else begin
        C_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_8_ce0 = 1'b1;
    end else begin
        C_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_9_ce0 = 1'b1;
    end else begin
        C_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_ce0 = 1'b1;
    end else begin
        C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln259_fu_295_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_w_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_w_1 = w_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sC1_blk_n = sC1_full_n;
    end else begin
        sC1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sC1_write = 1'b1;
    end else begin
        sC1_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_10_address0 = zext_ln259_fu_307_p1;

assign C_11_address0 = zext_ln259_fu_307_p1;

assign C_12_address0 = zext_ln259_fu_307_p1;

assign C_13_address0 = zext_ln259_fu_307_p1;

assign C_14_address0 = zext_ln259_fu_307_p1;

assign C_15_address0 = zext_ln259_fu_307_p1;

assign C_1_address0 = zext_ln259_fu_307_p1;

assign C_2_address0 = zext_ln259_fu_307_p1;

assign C_3_address0 = zext_ln259_fu_307_p1;

assign C_4_address0 = zext_ln259_fu_307_p1;

assign C_5_address0 = zext_ln259_fu_307_p1;

assign C_6_address0 = zext_ln259_fu_307_p1;

assign C_7_address0 = zext_ln259_fu_307_p1;

assign C_8_address0 = zext_ln259_fu_307_p1;

assign C_9_address0 = zext_ln259_fu_307_p1;

assign C_address0 = zext_ln259_fu_307_p1;

assign add_ln259_fu_301_p2 = (ap_sig_allocacmp_w_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (sC1_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln259_fu_295_p2 = ((ap_sig_allocacmp_w_1 == 5'd16) ? 1'b1 : 1'b0);

assign sC1_din = {{{{{{{{{{{{{{{{C_15_q0}, {C_14_q0}}, {C_13_q0}}, {C_12_q0}}, {C_11_q0}}, {C_10_q0}}, {C_9_q0}}, {C_8_q0}}, {C_7_q0}}, {C_6_q0}}, {C_5_q0}}, {C_4_q0}}, {C_3_q0}}, {C_2_q0}}, {C_1_q0}}, {C_q0}};

assign zext_ln259_fu_307_p1 = ap_sig_allocacmp_w_1;

endmodule //kyber_mult_inv_all_Pipeline_IN_WR
