// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ntt_kernel_ntt_kernel,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=51557960098,HLS_SYN_TPT=none,HLS_SYN_MEM=128,HLS_SYN_DSP=0,HLS_SYN_FF=5063,HLS_SYN_LUT=5208,HLS_VERSION=2023_2}" *)

module ntt_kernel (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 32'd1;
parameter    ap_ST_fsm_state2 = 32'd2;
parameter    ap_ST_fsm_state3 = 32'd4;
parameter    ap_ST_fsm_state4 = 32'd8;
parameter    ap_ST_fsm_state5 = 32'd16;
parameter    ap_ST_fsm_state6 = 32'd32;
parameter    ap_ST_fsm_state7 = 32'd64;
parameter    ap_ST_fsm_state8 = 32'd128;
parameter    ap_ST_fsm_state9 = 32'd256;
parameter    ap_ST_fsm_state10 = 32'd512;
parameter    ap_ST_fsm_state11 = 32'd1024;
parameter    ap_ST_fsm_state12 = 32'd2048;
parameter    ap_ST_fsm_state13 = 32'd4096;
parameter    ap_ST_fsm_state14 = 32'd8192;
parameter    ap_ST_fsm_state15 = 32'd16384;
parameter    ap_ST_fsm_state16 = 32'd32768;
parameter    ap_ST_fsm_state17 = 32'd65536;
parameter    ap_ST_fsm_state18 = 32'd131072;
parameter    ap_ST_fsm_state19 = 32'd262144;
parameter    ap_ST_fsm_state20 = 32'd524288;
parameter    ap_ST_fsm_state21 = 32'd1048576;
parameter    ap_ST_fsm_state22 = 32'd2097152;
parameter    ap_ST_fsm_state23 = 32'd4194304;
parameter    ap_ST_fsm_state24 = 32'd8388608;
parameter    ap_ST_fsm_state25 = 32'd16777216;
parameter    ap_ST_fsm_state26 = 32'd33554432;
parameter    ap_ST_fsm_state27 = 32'd67108864;
parameter    ap_ST_fsm_state28 = 32'd134217728;
parameter    ap_ST_fsm_state29 = 32'd268435456;
parameter    ap_ST_fsm_state30 = 32'd536870912;
parameter    ap_ST_fsm_state31 = 32'd1073741824;
parameter    ap_ST_fsm_state32 = 32'd2147483648;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] x;
wire   [63:0] psi_powers;
wire   [63:0] twiddles;
wire   [31:0] q;
wire   [31:0] q_inv;
wire   [31:0] batch_size;
wire   [31:0] n;
reg    gmem0_blk_n_AW;
wire    ap_CS_fsm_state25;
reg    gmem0_blk_n_B;
wire    ap_CS_fsm_state32;
reg    gmem1_blk_n_AR;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln59_reg_611;
reg    gmem2_blk_n_AR;
wire    ap_CS_fsm_state15;
reg   [31:0] n_read_reg_547;
reg   [31:0] batch_size_read_reg_555;
reg   [31:0] q_inv_read_reg_560;
reg   [31:0] q_read_reg_565;
reg   [63:0] twiddles_read_reg_571;
reg   [63:0] x_read_reg_576;
wire  signed [63:0] sext_ln59_fu_297_p1;
reg  signed [63:0] sext_ln59_reg_582;
wire  signed [61:0] trunc_ln1_fu_301_p4;
reg   [61:0] trunc_ln1_reg_587;
reg   [63:0] gmem1_addr_reg_592;
wire   [31:0] zext_ln59_1_fu_329_p1;
reg   [31:0] zext_ln59_1_reg_597;
wire   [61:0] zext_ln59_fu_333_p1;
reg   [61:0] zext_ln59_reg_603;
wire   [0:0] icmp_ln59_fu_359_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln59_2_fu_370_p2;
reg   [31:0] add_ln59_2_reg_621;
wire   [61:0] add_ln59_3_fu_375_p2;
reg   [61:0] add_ln59_3_reg_626;
wire   [30:0] add_ln59_1_fu_380_p2;
reg   [30:0] add_ln59_1_reg_631;
wire   [63:0] add_ln59_fu_392_p2;
reg   [63:0] add_ln59_reg_636;
wire    ap_CS_fsm_state11;
wire  signed [31:0] length_1_fu_412_p2;
reg  signed [31:0] length_1_reg_644;
wire    ap_CS_fsm_state13;
wire  signed [63:0] sext_ln82_fu_418_p1;
reg  signed [63:0] sext_ln82_reg_649;
wire   [15:0] trunc_ln82_fu_422_p1;
reg   [15:0] trunc_ln82_reg_654;
wire  signed [61:0] trunc_ln5_fu_443_p4;
reg   [61:0] trunc_ln5_reg_659;
reg   [63:0] gmem2_addr_reg_664;
wire   [31:0] zext_ln82_fu_471_p1;
reg   [31:0] zext_ln82_reg_669;
reg   [61:0] trunc_ln6_reg_674;
wire   [15:0] trunc_ln82_1_fu_501_p1;
reg   [15:0] trunc_ln82_1_reg_683;
wire    ap_CS_fsm_state14;
wire   [63:0] add_ln82_1_fu_505_p2;
reg   [63:0] add_ln82_1_reg_688;
wire   [31:0] offset_1_fu_510_p2;
reg   [15:0] local_x_address0;
reg    local_x_ce0;
wire   [31:0] local_x_q0;
reg   [15:0] local_x_address1;
reg    local_x_ce1;
reg    local_x_we1;
reg   [31:0] local_x_d1;
wire   [31:0] local_x_q1;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_start;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_done;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_idle;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_ready;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWVALID;
wire   [63:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWADDR;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWID;
wire   [31:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWLEN;
wire   [2:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWBURST;
wire   [1:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWPROT;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWQOS;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWREGION;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWUSER;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WVALID;
wire   [31:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WDATA;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WSTRB;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WLAST;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WID;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WUSER;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARVALID;
wire   [63:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARADDR;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARID;
wire   [31:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARLEN;
wire   [2:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARBURST;
wire   [1:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARPROT;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARQOS;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARREGION;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARUSER;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_RREADY;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_BREADY;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWVALID;
wire   [63:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWADDR;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWID;
wire   [31:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWLEN;
wire   [2:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWBURST;
wire   [1:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWPROT;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWQOS;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWREGION;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWUSER;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WVALID;
wire   [31:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WDATA;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WSTRB;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WLAST;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WID;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WUSER;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARVALID;
wire   [63:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARADDR;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARID;
wire   [31:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARLEN;
wire   [2:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARBURST;
wire   [1:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARPROT;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARQOS;
wire   [3:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARREGION;
wire   [0:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARUSER;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_RREADY;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_BREADY;
wire   [15:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_address1;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_ce1;
wire    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_we1;
wire   [31:0] grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_d1;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_start;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_done;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_idle;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_ready;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWVALID;
wire   [63:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWADDR;
wire   [0:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWID;
wire   [31:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWLEN;
wire   [2:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWSIZE;
wire   [1:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWBURST;
wire   [1:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWLOCK;
wire   [3:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWCACHE;
wire   [2:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWPROT;
wire   [3:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWQOS;
wire   [3:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWREGION;
wire   [0:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWUSER;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WVALID;
wire   [31:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WDATA;
wire   [3:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WSTRB;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WLAST;
wire   [0:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WID;
wire   [0:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WUSER;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARVALID;
wire   [63:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARADDR;
wire   [0:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARID;
wire   [31:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARLEN;
wire   [2:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARSIZE;
wire   [1:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARBURST;
wire   [1:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARLOCK;
wire   [3:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARCACHE;
wire   [2:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARPROT;
wire   [3:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARQOS;
wire   [3:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARREGION;
wire   [0:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARUSER;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_RREADY;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_BREADY;
wire   [15:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_address0;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_ce0;
wire   [15:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_address1;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_ce1;
wire    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_we1;
wire   [31:0] grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_d1;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_start;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_done;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_idle;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_ready;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWVALID;
wire   [63:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWADDR;
wire   [0:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWID;
wire   [31:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWLEN;
wire   [2:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWBURST;
wire   [1:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWPROT;
wire   [3:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWQOS;
wire   [3:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWREGION;
wire   [0:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWUSER;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WVALID;
wire   [31:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WDATA;
wire   [3:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WSTRB;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WLAST;
wire   [0:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WID;
wire   [0:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WUSER;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARVALID;
wire   [63:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARADDR;
wire   [0:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARID;
wire   [31:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARLEN;
wire   [2:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARBURST;
wire   [1:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARPROT;
wire   [3:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARQOS;
wire   [3:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARREGION;
wire   [0:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARUSER;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_RREADY;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_BREADY;
wire   [15:0] grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_local_x_address0;
wire    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_local_x_ce0;
reg    gmem0_AWVALID;
wire    gmem0_AWREADY;
reg   [63:0] gmem0_AWADDR;
reg   [31:0] gmem0_AWLEN;
reg    gmem0_WVALID;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [31:0] gmem0_RDATA;
wire   [8:0] gmem0_RFIFONUM;
wire    gmem0_BVALID;
reg    gmem0_BREADY;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
reg    gmem1_ARVALID;
wire    gmem1_ARREADY;
reg   [63:0] gmem1_ARADDR;
reg   [31:0] gmem1_ARLEN;
wire    gmem1_RVALID;
reg    gmem1_RREADY;
wire   [31:0] gmem1_RDATA;
wire   [8:0] gmem1_RFIFONUM;
wire    gmem1_BVALID;
wire    gmem2_AWREADY;
wire    gmem2_WREADY;
reg    gmem2_ARVALID;
wire    gmem2_ARREADY;
reg   [63:0] gmem2_ARADDR;
reg   [31:0] gmem2_ARLEN;
wire    gmem2_RVALID;
reg    gmem2_RREADY;
wire   [31:0] gmem2_RDATA;
wire   [8:0] gmem2_RFIFONUM;
wire    gmem2_BVALID;
reg   [31:0] offset_reg_215;
wire   [0:0] icmp_ln82_fu_496_p2;
wire    ap_CS_fsm_state12;
reg   [31:0] length_reg_227;
reg   [63:0] i_1_reg_239;
wire    ap_CS_fsm_state24;
wire   [0:0] icmp_ln79_fu_397_p2;
reg    grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_start_reg;
reg    grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_start_reg;
wire    ap_CS_fsm_state23;
reg    grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_start_reg;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire  signed [63:0] sext_ln70_fu_311_p1;
wire  signed [63:0] sext_ln85_fu_453_p1;
wire  signed [63:0] sext_ln104_fu_516_p1;
reg    ap_block_state3_io;
reg   [31:0] phi_mul1_fu_138;
reg   [61:0] phi_mul_fu_142;
reg   [30:0] b_fu_146;
wire  signed [31:0] trunc_ln38_fu_287_p0;
wire  signed [31:0] cmp213_fu_291_p0;
wire  signed [31:0] sext_ln59_fu_297_p0;
wire   [0:0] cmp213_fu_291_p2;
wire   [30:0] trunc_ln38_fu_287_p1;
wire   [30:0] empty_fu_321_p3;
wire  signed [31:0] zext_ln59_fu_333_p0;
wire   [31:0] zext_ln59_2_fu_355_p1;
wire   [63:0] shl_ln_fu_385_p3;
wire   [33:0] shl_ln82_1_fu_426_p3;
wire  signed [63:0] sext_ln82_1_fu_434_p1;
wire   [63:0] add_ln82_fu_438_p2;
wire   [0:0] cmp1915_fu_406_p2;
wire   [30:0] trunc_ln79_fu_402_p1;
wire   [30:0] empty_30_fu_463_p3;
reg   [31:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
reg    ap_ST_fsm_state32_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 32'd1;
#0 grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_start_reg = 1'b0;
#0 grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_start_reg = 1'b0;
#0 grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_start_reg = 1'b0;
#0 phi_mul1_fu_138 = 32'd0;
#0 phi_mul_fu_142 = 62'd0;
#0 b_fu_146 = 31'd0;
end

ntt_kernel_local_x_RAM_2P_BRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 65536 ),
    .AddressWidth( 16 ))
local_x_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(local_x_address0),
    .ce0(local_x_ce0),
    .q0(local_x_q0),
    .address1(local_x_address1),
    .ce1(local_x_ce1),
    .we1(local_x_we1),
    .d1(local_x_d1),
    .q1(local_x_q1)
);

ntt_kernel_ntt_kernel_Pipeline_PERMUTE_LOOP grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_start),
    .ap_done(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_done),
    .ap_idle(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_idle),
    .ap_ready(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_ready),
    .m_axi_gmem1_AWVALID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .m_axi_gmem0_AWVALID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .n(n_read_reg_547),
    .sext_ln70(trunc_ln1_reg_587),
    .phi_mul1(phi_mul1_fu_138),
    .x(x_read_reg_576),
    .local_x_address1(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_address1),
    .local_x_ce1(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_ce1),
    .local_x_we1(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_we1),
    .local_x_d1(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_d1)
);

ntt_kernel_ntt_kernel_Pipeline_BUTTERFLY_LOOP grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_start),
    .ap_done(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_done),
    .ap_idle(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_idle),
    .ap_ready(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_ready),
    .m_axi_gmem2_AWVALID(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(1'b0),
    .m_axi_gmem2_AWADDR(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(1'b0),
    .m_axi_gmem2_WDATA(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(gmem2_ARREADY),
    .m_axi_gmem2_ARADDR(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(gmem2_RVALID),
    .m_axi_gmem2_RREADY(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(gmem2_RDATA),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RFIFONUM(gmem2_RFIFONUM),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(1'b0),
    .m_axi_gmem2_BREADY(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(2'd0),
    .m_axi_gmem2_BID(1'd0),
    .m_axi_gmem2_BUSER(1'd0),
    .length_r(length_reg_227),
    .sext_ln85(trunc_ln5_reg_659),
    .local_x_address0(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_address0),
    .local_x_ce0(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_ce0),
    .local_x_q0(local_x_q0),
    .local_x_address1(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_address1),
    .local_x_ce1(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_ce1),
    .local_x_we1(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_we1),
    .local_x_d1(grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_d1),
    .local_x_q1(local_x_q1),
    .empty_23(trunc_ln82_1_reg_683),
    .empty(trunc_ln82_reg_654),
    .q_inv(q_inv_read_reg_560),
    .conv5_i(q_read_reg_565),
    .q(q_read_reg_565)
);

ntt_kernel_ntt_kernel_Pipeline_WRITE_BACK_LOOP grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_start),
    .ap_done(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_done),
    .ap_idle(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_idle),
    .ap_ready(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_ready),
    .m_axi_gmem0_AWVALID(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(gmem0_AWREADY),
    .m_axi_gmem0_AWADDR(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(gmem0_WREADY),
    .m_axi_gmem0_WDATA(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(1'b0),
    .m_axi_gmem0_ARADDR(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(1'b0),
    .m_axi_gmem0_RREADY(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(32'd0),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(9'd0),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(gmem0_BVALID),
    .m_axi_gmem0_BREADY(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .n(n_read_reg_547),
    .sext_ln104(trunc_ln6_reg_674),
    .local_x_address0(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_local_x_address0),
    .local_x_ce0(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_local_x_ce0),
    .local_x_q0(local_x_q0)
);

ntt_kernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .x(x),
    .psi_powers(psi_powers),
    .twiddles(twiddles),
    .q(q),
    .q_inv(q_inv),
    .batch_size(batch_size),
    .n(n),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

ntt_kernel_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARADDR),
    .I_ARLEN(grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARLEN),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RFIFONUM(gmem0_RFIFONUM),
    .I_AWVALID(gmem0_AWVALID),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(gmem0_AWADDR),
    .I_AWLEN(gmem0_AWLEN),
    .I_WVALID(gmem0_WVALID),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WDATA),
    .I_WSTRB(grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WSTRB),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(gmem0_BREADY)
);

ntt_kernel_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(gmem1_ARADDR),
    .I_ARLEN(gmem1_ARLEN),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RFIFONUM(gmem1_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0)
);

ntt_kernel_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem2_ARVALID),
    .I_ARREADY(gmem2_ARREADY),
    .I_ARADDR(gmem2_ARADDR),
    .I_ARLEN(gmem2_ARLEN),
    .I_RVALID(gmem2_RVALID),
    .I_RREADY(gmem2_RREADY),
    .I_RDATA(gmem2_RDATA),
    .I_RFIFONUM(gmem2_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem2_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem2_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem2_BVALID),
    .I_BREADY(1'b0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_start_reg <= 1'b1;
        end else if ((grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_ready == 1'b1)) begin
            grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_start_reg <= 1'b1;
        end else if ((grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_ready == 1'b1)) begin
            grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state26)) begin
            grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_start_reg <= 1'b1;
        end else if ((grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_ready == 1'b1)) begin
            grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_fu_146 <= 31'd0;
    end else if (((icmp_ln79_fu_397_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        b_fu_146 <= add_ln59_1_reg_631;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln79_fu_397_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        i_1_reg_239 <= 64'd0;
    end else if (((grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        i_1_reg_239 <= add_ln82_1_reg_688;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        length_reg_227 <= 32'd1;
    end else if (((icmp_ln82_fu_496_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        length_reg_227 <= length_1_reg_644;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        offset_reg_215 <= 32'd0;
    end else if (((icmp_ln82_fu_496_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        offset_reg_215 <= offset_1_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul1_fu_138 <= 32'd0;
    end else if (((icmp_ln79_fu_397_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        phi_mul1_fu_138 <= add_ln59_2_reg_621;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_fu_142 <= 62'd0;
    end else if (((icmp_ln79_fu_397_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        phi_mul_fu_142 <= add_ln59_3_reg_626;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln59_1_reg_631 <= add_ln59_1_fu_380_p2;
        add_ln59_2_reg_621 <= add_ln59_2_fu_370_p2;
        add_ln59_3_reg_626 <= add_ln59_3_fu_375_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln59_reg_636 <= add_ln59_fu_392_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add_ln82_1_reg_688 <= add_ln82_1_fu_505_p2;
        trunc_ln82_1_reg_683 <= trunc_ln82_1_fu_501_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        batch_size_read_reg_555 <= batch_size;
        gmem1_addr_reg_592 <= sext_ln70_fu_311_p1;
        n_read_reg_547 <= n;
        q_inv_read_reg_560 <= q_inv;
        q_read_reg_565 <= q;
        sext_ln59_reg_582 <= sext_ln59_fu_297_p1;
        trunc_ln1_reg_587 <= {{psi_powers[63:2]}};
        twiddles_read_reg_571 <= twiddles;
        x_read_reg_576 <= x;
        zext_ln59_1_reg_597[30 : 0] <= zext_ln59_1_fu_329_p1[30 : 0];
        zext_ln59_reg_603[31 : 0] <= zext_ln59_fu_333_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        gmem2_addr_reg_664 <= sext_ln85_fu_453_p1;
        length_1_reg_644[31 : 1] <= length_1_fu_412_p2[31 : 1];
        sext_ln82_reg_649[63 : 1] <= sext_ln82_fu_418_p1[63 : 1];
        trunc_ln5_reg_659 <= {{add_ln82_fu_438_p2[63:2]}};
        trunc_ln6_reg_674 <= {{add_ln59_reg_636[63:2]}};
        trunc_ln82_reg_654 <= trunc_ln82_fu_422_p1;
        zext_ln82_reg_669[30 : 0] <= zext_ln82_fu_471_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln59_reg_611 <= icmp_ln59_fu_359_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((gmem2_ARREADY == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

always @ (*) begin
    if ((gmem0_BVALID == 1'b0)) begin
        ap_ST_fsm_state32_blk = 1'b1;
    end else begin
        ap_ST_fsm_state32_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_io)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (icmp_ln59_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (icmp_ln59_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem0_ARVALID = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_ARVALID;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        gmem0_AWADDR = sext_ln104_fu_516_p1;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26))) begin
        gmem0_AWADDR = grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWADDR;
    end else begin
        gmem0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        gmem0_AWLEN = zext_ln59_1_reg_597;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26))) begin
        gmem0_AWLEN = grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWLEN;
    end else begin
        gmem0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        gmem0_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26))) begin
        gmem0_AWVALID = grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_AWVALID;
    end else begin
        gmem0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
        gmem0_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26))) begin
        gmem0_BREADY = grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_BREADY;
    end else begin
        gmem0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem0_RREADY = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem0_RREADY;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26))) begin
        gmem0_WVALID = grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_m_axi_gmem0_WVALID;
    end else begin
        gmem0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        gmem0_blk_n_AW = m_axi_gmem0_AWREADY;
    end else begin
        gmem0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        gmem0_blk_n_B = m_axi_gmem0_BVALID;
    end else begin
        gmem0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (icmp_ln59_reg_611 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_ARADDR = gmem1_addr_reg_592;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem1_ARADDR = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARADDR;
    end else begin
        gmem1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (icmp_ln59_reg_611 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_ARLEN = zext_ln59_1_reg_597;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem1_ARLEN = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARLEN;
    end else begin
        gmem1_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (icmp_ln59_reg_611 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem1_ARVALID = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_ARVALID;
    end else begin
        gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem1_RREADY = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_m_axi_gmem1_RREADY;
    end else begin
        gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln59_reg_611 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((gmem2_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gmem2_ARADDR = gmem2_addr_reg_664;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem2_ARADDR = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARADDR;
    end else begin
        gmem2_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem2_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gmem2_ARLEN = zext_ln82_reg_669;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem2_ARLEN = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARLEN;
    end else begin
        gmem2_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem2_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gmem2_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem2_ARVALID = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_ARVALID;
    end else begin
        gmem2_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem2_RREADY = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_m_axi_gmem2_RREADY;
    end else begin
        gmem2_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gmem2_blk_n_AR = m_axi_gmem2_ARREADY;
    end else begin
        gmem2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        local_x_address0 = grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_local_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        local_x_address0 = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_address0;
    end else begin
        local_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        local_x_address1 = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_address1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        local_x_address1 = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_address1;
    end else begin
        local_x_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        local_x_ce0 = grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_local_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        local_x_ce0 = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_ce0;
    end else begin
        local_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        local_x_ce1 = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_ce1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        local_x_ce1 = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_ce1;
    end else begin
        local_x_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        local_x_d1 = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_d1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        local_x_d1 = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_d1;
    end else begin
        local_x_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        local_x_we1 = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_local_x_we1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        local_x_we1 = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_local_x_we1;
    end else begin
        local_x_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_io) & (icmp_ln59_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state3_io) & (icmp_ln59_reg_611 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((icmp_ln79_fu_397_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln82_fu_496_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((gmem2_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((gmem0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln59_1_fu_380_p2 = (b_fu_146 + 31'd1);

assign add_ln59_2_fu_370_p2 = (phi_mul1_fu_138 + n_read_reg_547);

assign add_ln59_3_fu_375_p2 = (phi_mul_fu_142 + zext_ln59_reg_603);

assign add_ln59_fu_392_p2 = (shl_ln_fu_385_p3 + x_read_reg_576);

assign add_ln82_1_fu_505_p2 = ($signed(sext_ln82_reg_649) + $signed(i_1_reg_239));

assign add_ln82_fu_438_p2 = ($signed(sext_ln82_1_fu_434_p1) + $signed(twiddles_read_reg_571));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

always @ (*) begin
    ap_block_state3_io = ((gmem1_ARREADY == 1'b0) & (icmp_ln59_reg_611 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp1915_fu_406_p2 = (($signed(length_reg_227) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign cmp213_fu_291_p0 = n;

assign cmp213_fu_291_p2 = (($signed(cmp213_fu_291_p0) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_30_fu_463_p3 = ((cmp1915_fu_406_p2[0:0] == 1'b1) ? trunc_ln79_fu_402_p1 : 31'd0);

assign empty_fu_321_p3 = ((cmp213_fu_291_p2[0:0] == 1'b1) ? trunc_ln38_fu_287_p1 : 31'd0);

assign grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_start = grp_ntt_kernel_Pipeline_BUTTERFLY_LOOP_fu_263_ap_start_reg;

assign grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_start = grp_ntt_kernel_Pipeline_PERMUTE_LOOP_fu_250_ap_start_reg;

assign grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_start = grp_ntt_kernel_Pipeline_WRITE_BACK_LOOP_fu_278_ap_start_reg;

assign icmp_ln59_fu_359_p2 = (($signed(zext_ln59_2_fu_355_p1) < $signed(batch_size_read_reg_555)) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_397_p2 = (($signed(length_reg_227) < $signed(n_read_reg_547)) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_496_p2 = (($signed(i_1_reg_239) < $signed(sext_ln59_reg_582)) ? 1'b1 : 1'b0);

assign length_1_fu_412_p2 = length_reg_227 << 32'd1;

assign offset_1_fu_510_p2 = (length_reg_227 + offset_reg_215);

assign sext_ln104_fu_516_p1 = $signed(trunc_ln6_reg_674);

assign sext_ln59_fu_297_p0 = n;

assign sext_ln59_fu_297_p1 = sext_ln59_fu_297_p0;

assign sext_ln70_fu_311_p1 = trunc_ln1_fu_301_p4;

assign sext_ln82_1_fu_434_p1 = $signed(shl_ln82_1_fu_426_p3);

assign sext_ln82_fu_418_p1 = length_1_fu_412_p2;

assign sext_ln85_fu_453_p1 = trunc_ln5_fu_443_p4;

assign shl_ln82_1_fu_426_p3 = {{offset_reg_215}, {2'd0}};

assign shl_ln_fu_385_p3 = {{phi_mul_fu_142}, {2'd0}};

assign trunc_ln1_fu_301_p4 = {{psi_powers[63:2]}};

assign trunc_ln38_fu_287_p0 = n;

assign trunc_ln38_fu_287_p1 = trunc_ln38_fu_287_p0[30:0];

assign trunc_ln5_fu_443_p4 = {{add_ln82_fu_438_p2[63:2]}};

assign trunc_ln79_fu_402_p1 = length_reg_227[30:0];

assign trunc_ln82_1_fu_501_p1 = i_1_reg_239[15:0];

assign trunc_ln82_fu_422_p1 = length_reg_227[15:0];

assign zext_ln59_1_fu_329_p1 = empty_fu_321_p3;

assign zext_ln59_2_fu_355_p1 = b_fu_146;

assign zext_ln59_fu_333_p0 = n;

assign zext_ln59_fu_333_p1 = $unsigned(zext_ln59_fu_333_p0);

assign zext_ln82_fu_471_p1 = empty_30_fu_463_p3;

always @ (posedge ap_clk) begin
    zext_ln59_1_reg_597[31] <= 1'b0;
    zext_ln59_reg_603[61:32] <= 30'b000000000000000000000000000000;
    length_1_reg_644[0] <= 1'b0;
    sext_ln82_reg_649[0] <= 1'b0;
    zext_ln82_reg_669[31] <= 1'b0;
end

endmodule //ntt_kernel
