-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity kyber_mult_basemul_p_ZL5BM_MW_3_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 16; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of kyber_mult_basemul_p_ZL5BM_MW_3_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0010101110101101", 1 => "0011010001001010", 2 => "1100100001100110", 3 => "1010101101101000", 
    4 => "0011001101001010", 5 => "1110111000010101", 6 => "0101101000110100", 7 => "0001010101110100", 
    8 => "1000000100001001", 9 => "0111011001101101", 10 => "1011011011001010", 11 => "0011000101011110", 
    12 => "0100111010000011", 13 => "0100100001011100", 14 => "0100110001001000", 15 => "1100111010110101", 
    16 => "0100111101001000", 17 => "0000100001100001", 18 => "0011101111111011", 19 => "1000000101111111", 
    20 => "1110011101111000", 21 => "1100010111001001", 22 => "1101010011011011", 23 => "0011100010000101", 
    24 => "1010110000000110", 25 => "1011000100011001", 26 => "0101101010101010", 27 => "1011101111011101", 
    28 => "1010001011001100", 29 => "1011000011011110", 30 => "0001111001001100", 31 => "0101101001011011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

