// SPDX-FileCopyrightText: 2020 Efabless Corporation
// SPDX-License-Identifier: Apache-2.0
// GENERATED by scripts/gen_ntt_v.py from lef/ntt_engine_256.lef. Do not hand-edit.

`default_nettype none

// Physical integration shell around hardened macros. The wrapper flow flattens
// this shell, leaving u_bridge, u_engine and eight ntt_repeater instances as hard
// macros inside user_project_wrapper. See scripts/gen_ntt_v.py for the scheme.
//
// Signal map (chain/bit/direction/entry-or-exit stage):
//   w 0 up   stage 3  slot_a[1] (N edge)
//   w 1 up   stage 3  slot_b[0] (N edge)
//   w 2 up   stage 3  slot_c[1] (W edge)
//   w 3 up   stage 3  mem_target (N edge)
//   w 4 up   stage 3  mem_addr[5] (W edge)
//   w 5 up   stage 3  mem_wdata[15] (W edge)
//   w 6 up   stage 3  mem_wdata[17] (N edge)
//   w 7 up   stage 3  mem_wdata[21] (W edge)
//   w 8 up   stage 3  mem_wdata[22] (N edge)
//   w 9 up   stage 3  mem_wdata[26] (N edge)
//   w10 up   stage 2  op[0] (W edge)
//   w11 up   stage 2  mem_wdata[2] (W edge)
//   w12 up   stage 2  mem_wdata[8] (W edge)
//   w13 up   stage 2  mem_wdata[19] (W edge)
//   w14 up   stage 2  mem_wdata[29] (W edge)
//   w15 up   stage 1  slot_c[0] (W edge)
//   w16 up   stage 1  mac_init (W edge)
//   w17 up   stage 1  mem_wdata[7] (W edge)
//   w18 up   stage 1  mem_wdata[14] (W edge)
//   w19 up   stage 1  mem_wdata[28] (W edge)
//   w20 up   stage 0  mem_wdata[24] (W edge)
//   w21 spare
//   w22 down stage 3  busy (N edge)
//   w23 down stage 3  mem_rdata[3] (N edge)
//   w24 down stage 3  mem_rdata[9] (W edge)
//   w25 down stage 3  mem_rdata[11] (N edge)
//   w26 down stage 3  mem_rdata[12] (N edge)
//   w27 down stage 3  mem_rdata[23] (N edge)
//   w28 down stage 3  mem_rdata[27] (N edge)
//   w29 down stage 2  mem_rdata[6] (W edge)
//   w30 down stage 2  mem_rdata[7] (W edge)
//   w31 down stage 2  mem_rdata[10] (W edge)
//   w32 down stage 2  mem_rdata[25] (W edge)
//   w33 down stage 1  mem_rdata[13] (W edge)
//   w34 down stage 1  mem_rdata[24] (W edge)
//   w35 down stage 1  mem_rdata[30] (W edge)
//   w36 spare
//   w37 spare
//   w38 spare
//   w39 spare
//   e 0 up   stage 3  rst_n (N edge)
//   e 1 up   stage 3  slot_a[0] (N edge)
//   e 2 up   stage 3  mem_slot[1] (E edge)
//   e 3 up   stage 3  mem_addr[2] (N edge)
//   e 4 up   stage 3  mem_addr[4] (E edge)
//   e 5 up   stage 3  mem_addr[7] (N edge)
//   e 6 up   stage 3  mem_wdata[3] (N edge)
//   e 7 up   stage 3  mem_wdata[5] (E edge)
//   e 8 up   stage 3  mem_wdata[27] (N edge)
//   e 9 up   stage 3  mem_wdata[31] (N edge)
//   e10 up   stage 2  start (E edge)
//   e11 up   stage 2  op[1] (E edge)
//   e12 up   stage 2  mem_addr[3] (E edge)
//   e13 up   stage 2  mem_addr[8] (E edge)
//   e14 up   stage 2  mem_wdata[12] (E edge)
//   e15 up   stage 2  mem_wdata[20] (E edge)
//   e16 up   stage 1  mem_addr[1] (E edge)
//   e17 up   stage 1  mem_wdata[6] (E edge)
//   e18 up   stage 1  mem_wdata[13] (E edge)
//   e19 up   stage 1  mem_wdata[16] (E edge)
//   e20 up   stage 1  mem_wdata[18] (E edge)
//   e21 spare
//   e22 down stage 3  mem_rdata[1] (N edge)
//   e23 down stage 3  mem_rdata[2] (N edge)
//   e24 down stage 3  mem_rdata[4] (E edge)
//   e25 down stage 3  mem_rdata[14] (E edge)
//   e26 down stage 3  mem_rdata[16] (N edge)
//   e27 down stage 3  mem_rdata[21] (N edge)
//   e28 down stage 3  mem_rdata[22] (E edge)
//   e29 down stage 2  mem_rdata[8] (E edge)
//   e30 down stage 2  mem_rdata[18] (E edge)
//   e31 down stage 2  mem_rdata[28] (E edge)
//   e32 down stage 1  mem_rdata[15] (E edge)
//   e33 down stage 1  mem_rdata[20] (E edge)
//   e34 down stage 1  mem_rdata[29] (E edge)
//   e35 spare
//   e36 spare
//   e37 spare
//   e38 spare
//   e39 spare
module ntt (
`ifdef USE_POWER_PINS
    inout  wire        vccd1,
    inout  wire        vssd1,
`endif
    input  wire        wb_clk_i,
    input  wire        wb_rst_i,
    input  wire        wbs_stb_i,
    input  wire        wbs_cyc_i,
    input  wire        wbs_we_i,
    input  wire [3:0]  wbs_sel_i,
    input  wire [31:0] wbs_dat_i,
    input  wire [31:0] wbs_adr_i,
    output wire        wbs_ack_o,
    output wire [31:0] wbs_dat_o,
    output wire [127:0] la_data_out_o,
    output wire [37:0]  io_out_o,
    output wire [37:0]  io_oeb_o,
    output wire [2:0]   user_irq_o,
    output wire        busy_o,
    output wire        done_o,
    output wire        ext_rvalid_o
);

    wire engine_rst_n;
    wire e_rst_n;
    wire start;
    wire e_start;
    wire [2:0] op;
    wire [2:0] e_op;
    wire [1:0] slot_a;
    wire [1:0] e_slot_a;
    wire [1:0] slot_b;
    wire [1:0] e_slot_b;
    wire [1:0] slot_c;
    wire [1:0] e_slot_c;
    wire mac_init;
    wire e_mac_init;
    wire mem_we;
    wire e_mem_we;
    wire mem_re;
    wire e_mem_re;
    wire mem_target;
    wire e_mem_target;
    wire [1:0] mem_slot;
    wire [1:0] e_mem_slot;
    wire [8:0] mem_addr;
    wire [8:0] e_mem_addr;
    wire [31:0] mem_wdata;
    wire [31:0] e_mem_wdata;
    wire busy_e;
    wire busy_b;
    wire done;
    wire [31:0] mem_rdata_e;
    wire [31:0] mem_rdata_b;
    wire mem_rvalid;
    wire [39:0] w0_a, w0_y;
    wire [39:0] w1_a, w1_y;
    wire [39:0] w2_a, w2_y;
    wire [39:0] w3_a, w3_y;
    wire [39:0] e0_a, e0_y;
    wire [39:0] e1_a, e1_y;
    wire [39:0] e2_a, e2_y;
    wire [39:0] e3_a, e3_y;

    assign busy_o       = busy_b;
    assign done_o       = done;
    assign ext_rvalid_o = mem_rvalid;

    // ---- direct (south-edge) connections ----
    assign e_op[2] = op[2];
    assign e_slot_b[1] = slot_b[1];
    assign e_mem_we = mem_we;
    assign e_mem_re = mem_re;
    assign e_mem_slot[0] = mem_slot[0];
    assign e_mem_addr[0] = mem_addr[0];
    assign e_mem_addr[6] = mem_addr[6];
    assign e_mem_wdata[0] = mem_wdata[0];
    assign e_mem_wdata[1] = mem_wdata[1];
    assign e_mem_wdata[4] = mem_wdata[4];
    assign e_mem_wdata[9] = mem_wdata[9];
    assign e_mem_wdata[10] = mem_wdata[10];
    assign e_mem_wdata[11] = mem_wdata[11];
    assign e_mem_wdata[23] = mem_wdata[23];
    assign e_mem_wdata[25] = mem_wdata[25];
    assign e_mem_wdata[30] = mem_wdata[30];
    assign mem_rdata_b[0] = mem_rdata_e[0];
    assign mem_rdata_b[5] = mem_rdata_e[5];
    assign mem_rdata_b[17] = mem_rdata_e[17];
    assign mem_rdata_b[19] = mem_rdata_e[19];
    assign mem_rdata_b[26] = mem_rdata_e[26];
    assign mem_rdata_b[31] = mem_rdata_e[31];

    // ---- west chain ----
    assign w0_a[0] = slot_a[1];
    assign w1_a[0] = w0_y[0];
    assign w2_a[0] = w1_y[0];
    assign w3_a[0] = w2_y[0];
    assign e_slot_a[1] = w3_y[0];
    assign w0_a[1] = slot_b[0];
    assign w1_a[1] = w0_y[1];
    assign w2_a[1] = w1_y[1];
    assign w3_a[1] = w2_y[1];
    assign e_slot_b[0] = w3_y[1];
    assign w0_a[2] = slot_c[1];
    assign w1_a[2] = w0_y[2];
    assign w2_a[2] = w1_y[2];
    assign w3_a[2] = w2_y[2];
    assign e_slot_c[1] = w3_y[2];
    assign w0_a[3] = mem_target;
    assign w1_a[3] = w0_y[3];
    assign w2_a[3] = w1_y[3];
    assign w3_a[3] = w2_y[3];
    assign e_mem_target = w3_y[3];
    assign w0_a[4] = mem_addr[5];
    assign w1_a[4] = w0_y[4];
    assign w2_a[4] = w1_y[4];
    assign w3_a[4] = w2_y[4];
    assign e_mem_addr[5] = w3_y[4];
    assign w0_a[5] = mem_wdata[15];
    assign w1_a[5] = w0_y[5];
    assign w2_a[5] = w1_y[5];
    assign w3_a[5] = w2_y[5];
    assign e_mem_wdata[15] = w3_y[5];
    assign w0_a[6] = mem_wdata[17];
    assign w1_a[6] = w0_y[6];
    assign w2_a[6] = w1_y[6];
    assign w3_a[6] = w2_y[6];
    assign e_mem_wdata[17] = w3_y[6];
    assign w0_a[7] = mem_wdata[21];
    assign w1_a[7] = w0_y[7];
    assign w2_a[7] = w1_y[7];
    assign w3_a[7] = w2_y[7];
    assign e_mem_wdata[21] = w3_y[7];
    assign w0_a[8] = mem_wdata[22];
    assign w1_a[8] = w0_y[8];
    assign w2_a[8] = w1_y[8];
    assign w3_a[8] = w2_y[8];
    assign e_mem_wdata[22] = w3_y[8];
    assign w0_a[9] = mem_wdata[26];
    assign w1_a[9] = w0_y[9];
    assign w2_a[9] = w1_y[9];
    assign w3_a[9] = w2_y[9];
    assign e_mem_wdata[26] = w3_y[9];
    assign w0_a[10] = op[0];
    assign w1_a[10] = w0_y[10];
    assign w2_a[10] = w1_y[10];
    assign w3_a[10] = w3_y[22];
    assign e_op[0] = w2_y[10];
    assign w0_a[11] = mem_wdata[2];
    assign w1_a[11] = w0_y[11];
    assign w2_a[11] = w1_y[11];
    assign w3_a[11] = w3_y[22];
    assign e_mem_wdata[2] = w2_y[11];
    assign w0_a[12] = mem_wdata[8];
    assign w1_a[12] = w0_y[12];
    assign w2_a[12] = w1_y[12];
    assign w3_a[12] = w3_y[22];
    assign e_mem_wdata[8] = w2_y[12];
    assign w0_a[13] = mem_wdata[19];
    assign w1_a[13] = w0_y[13];
    assign w2_a[13] = w1_y[13];
    assign w3_a[13] = w3_y[22];
    assign e_mem_wdata[19] = w2_y[13];
    assign w0_a[14] = mem_wdata[29];
    assign w1_a[14] = w0_y[14];
    assign w2_a[14] = w1_y[14];
    assign w3_a[14] = w3_y[22];
    assign e_mem_wdata[29] = w2_y[14];
    assign w0_a[15] = slot_c[0];
    assign w1_a[15] = w0_y[15];
    assign w2_a[15] = w2_y[22];
    assign w3_a[15] = w3_y[22];
    assign e_slot_c[0] = w1_y[15];
    assign w0_a[16] = mac_init;
    assign w1_a[16] = w0_y[16];
    assign w2_a[16] = w2_y[22];
    assign w3_a[16] = w3_y[22];
    assign e_mac_init = w1_y[16];
    assign w0_a[17] = mem_wdata[7];
    assign w1_a[17] = w0_y[17];
    assign w2_a[17] = w2_y[22];
    assign w3_a[17] = w3_y[22];
    assign e_mem_wdata[7] = w1_y[17];
    assign w0_a[18] = mem_wdata[14];
    assign w1_a[18] = w0_y[18];
    assign w2_a[18] = w2_y[22];
    assign w3_a[18] = w3_y[22];
    assign e_mem_wdata[14] = w1_y[18];
    assign w0_a[19] = mem_wdata[28];
    assign w1_a[19] = w0_y[19];
    assign w2_a[19] = w2_y[22];
    assign w3_a[19] = w3_y[22];
    assign e_mem_wdata[28] = w1_y[19];
    assign w0_a[20] = mem_wdata[24];
    assign w1_a[20] = w1_y[22];
    assign w2_a[20] = w2_y[22];
    assign w3_a[20] = w3_y[22];
    assign e_mem_wdata[24] = w0_y[20];
    assign w0_a[21] = w0_y[22];
    assign w1_a[21] = w1_y[22];
    assign w2_a[21] = w2_y[22];
    assign w3_a[21] = w3_y[22];
    assign w0_a[22] = w1_y[22];
    assign w1_a[22] = w2_y[22];
    assign w2_a[22] = w3_y[22];
    assign w3_a[22] = busy_e;
    assign busy_b = w0_y[22];
    assign w0_a[23] = w1_y[23];
    assign w1_a[23] = w2_y[23];
    assign w2_a[23] = w3_y[23];
    assign w3_a[23] = mem_rdata_e[3];
    assign mem_rdata_b[3] = w0_y[23];
    assign w0_a[24] = w1_y[24];
    assign w1_a[24] = w2_y[24];
    assign w2_a[24] = w3_y[24];
    assign w3_a[24] = mem_rdata_e[9];
    assign mem_rdata_b[9] = w0_y[24];
    assign w0_a[25] = w1_y[25];
    assign w1_a[25] = w2_y[25];
    assign w2_a[25] = w3_y[25];
    assign w3_a[25] = mem_rdata_e[11];
    assign mem_rdata_b[11] = w0_y[25];
    assign w0_a[26] = w1_y[26];
    assign w1_a[26] = w2_y[26];
    assign w2_a[26] = w3_y[26];
    assign w3_a[26] = mem_rdata_e[12];
    assign mem_rdata_b[12] = w0_y[26];
    assign w0_a[27] = w1_y[27];
    assign w1_a[27] = w2_y[27];
    assign w2_a[27] = w3_y[27];
    assign w3_a[27] = mem_rdata_e[23];
    assign mem_rdata_b[23] = w0_y[27];
    assign w0_a[28] = w1_y[28];
    assign w1_a[28] = w2_y[28];
    assign w2_a[28] = w3_y[28];
    assign w3_a[28] = mem_rdata_e[27];
    assign mem_rdata_b[27] = w0_y[28];
    assign w0_a[29] = w1_y[29];
    assign w1_a[29] = w2_y[29];
    assign w2_a[29] = mem_rdata_e[6];
    assign w3_a[29] = w3_y[0];
    assign mem_rdata_b[6] = w0_y[29];
    assign w0_a[30] = w1_y[30];
    assign w1_a[30] = w2_y[30];
    assign w2_a[30] = mem_rdata_e[7];
    assign w3_a[30] = w3_y[0];
    assign mem_rdata_b[7] = w0_y[30];
    assign w0_a[31] = w1_y[31];
    assign w1_a[31] = w2_y[31];
    assign w2_a[31] = mem_rdata_e[10];
    assign w3_a[31] = w3_y[0];
    assign mem_rdata_b[10] = w0_y[31];
    assign w0_a[32] = w1_y[32];
    assign w1_a[32] = w2_y[32];
    assign w2_a[32] = mem_rdata_e[25];
    assign w3_a[32] = w3_y[0];
    assign mem_rdata_b[25] = w0_y[32];
    assign w0_a[33] = w1_y[33];
    assign w1_a[33] = mem_rdata_e[13];
    assign w2_a[33] = w2_y[0];
    assign w3_a[33] = w3_y[0];
    assign mem_rdata_b[13] = w0_y[33];
    assign w0_a[34] = w1_y[34];
    assign w1_a[34] = mem_rdata_e[24];
    assign w2_a[34] = w2_y[0];
    assign w3_a[34] = w3_y[0];
    assign mem_rdata_b[24] = w0_y[34];
    assign w0_a[35] = w1_y[35];
    assign w1_a[35] = mem_rdata_e[30];
    assign w2_a[35] = w2_y[0];
    assign w3_a[35] = w3_y[0];
    assign mem_rdata_b[30] = w0_y[35];
    assign w0_a[36] = w0_y[0];
    assign w1_a[36] = w1_y[0];
    assign w2_a[36] = w2_y[0];
    assign w3_a[36] = w3_y[0];
    assign w0_a[37] = w0_y[0];
    assign w1_a[37] = w1_y[0];
    assign w2_a[37] = w2_y[0];
    assign w3_a[37] = w3_y[0];
    assign w0_a[38] = w0_y[0];
    assign w1_a[38] = w1_y[0];
    assign w2_a[38] = w2_y[0];
    assign w3_a[38] = w3_y[0];
    assign w0_a[39] = w0_y[0];
    assign w1_a[39] = w1_y[0];
    assign w2_a[39] = w2_y[0];
    assign w3_a[39] = w3_y[0];

    // ---- east chain ----
    assign e0_a[0] = engine_rst_n;
    assign e1_a[0] = e0_y[0];
    assign e2_a[0] = e1_y[0];
    assign e3_a[0] = e2_y[0];
    assign e_rst_n = e3_y[0];
    assign e0_a[1] = slot_a[0];
    assign e1_a[1] = e0_y[1];
    assign e2_a[1] = e1_y[1];
    assign e3_a[1] = e2_y[1];
    assign e_slot_a[0] = e3_y[1];
    assign e0_a[2] = mem_slot[1];
    assign e1_a[2] = e0_y[2];
    assign e2_a[2] = e1_y[2];
    assign e3_a[2] = e2_y[2];
    assign e_mem_slot[1] = e3_y[2];
    assign e0_a[3] = mem_addr[2];
    assign e1_a[3] = e0_y[3];
    assign e2_a[3] = e1_y[3];
    assign e3_a[3] = e2_y[3];
    assign e_mem_addr[2] = e3_y[3];
    assign e0_a[4] = mem_addr[4];
    assign e1_a[4] = e0_y[4];
    assign e2_a[4] = e1_y[4];
    assign e3_a[4] = e2_y[4];
    assign e_mem_addr[4] = e3_y[4];
    assign e0_a[5] = mem_addr[7];
    assign e1_a[5] = e0_y[5];
    assign e2_a[5] = e1_y[5];
    assign e3_a[5] = e2_y[5];
    assign e_mem_addr[7] = e3_y[5];
    assign e0_a[6] = mem_wdata[3];
    assign e1_a[6] = e0_y[6];
    assign e2_a[6] = e1_y[6];
    assign e3_a[6] = e2_y[6];
    assign e_mem_wdata[3] = e3_y[6];
    assign e0_a[7] = mem_wdata[5];
    assign e1_a[7] = e0_y[7];
    assign e2_a[7] = e1_y[7];
    assign e3_a[7] = e2_y[7];
    assign e_mem_wdata[5] = e3_y[7];
    assign e0_a[8] = mem_wdata[27];
    assign e1_a[8] = e0_y[8];
    assign e2_a[8] = e1_y[8];
    assign e3_a[8] = e2_y[8];
    assign e_mem_wdata[27] = e3_y[8];
    assign e0_a[9] = mem_wdata[31];
    assign e1_a[9] = e0_y[9];
    assign e2_a[9] = e1_y[9];
    assign e3_a[9] = e2_y[9];
    assign e_mem_wdata[31] = e3_y[9];
    assign e0_a[10] = start;
    assign e1_a[10] = e0_y[10];
    assign e2_a[10] = e1_y[10];
    assign e3_a[10] = e3_y[22];
    assign e_start = e2_y[10];
    assign e0_a[11] = op[1];
    assign e1_a[11] = e0_y[11];
    assign e2_a[11] = e1_y[11];
    assign e3_a[11] = e3_y[22];
    assign e_op[1] = e2_y[11];
    assign e0_a[12] = mem_addr[3];
    assign e1_a[12] = e0_y[12];
    assign e2_a[12] = e1_y[12];
    assign e3_a[12] = e3_y[22];
    assign e_mem_addr[3] = e2_y[12];
    assign e0_a[13] = mem_addr[8];
    assign e1_a[13] = e0_y[13];
    assign e2_a[13] = e1_y[13];
    assign e3_a[13] = e3_y[22];
    assign e_mem_addr[8] = e2_y[13];
    assign e0_a[14] = mem_wdata[12];
    assign e1_a[14] = e0_y[14];
    assign e2_a[14] = e1_y[14];
    assign e3_a[14] = e3_y[22];
    assign e_mem_wdata[12] = e2_y[14];
    assign e0_a[15] = mem_wdata[20];
    assign e1_a[15] = e0_y[15];
    assign e2_a[15] = e1_y[15];
    assign e3_a[15] = e3_y[22];
    assign e_mem_wdata[20] = e2_y[15];
    assign e0_a[16] = mem_addr[1];
    assign e1_a[16] = e0_y[16];
    assign e2_a[16] = e2_y[22];
    assign e3_a[16] = e3_y[22];
    assign e_mem_addr[1] = e1_y[16];
    assign e0_a[17] = mem_wdata[6];
    assign e1_a[17] = e0_y[17];
    assign e2_a[17] = e2_y[22];
    assign e3_a[17] = e3_y[22];
    assign e_mem_wdata[6] = e1_y[17];
    assign e0_a[18] = mem_wdata[13];
    assign e1_a[18] = e0_y[18];
    assign e2_a[18] = e2_y[22];
    assign e3_a[18] = e3_y[22];
    assign e_mem_wdata[13] = e1_y[18];
    assign e0_a[19] = mem_wdata[16];
    assign e1_a[19] = e0_y[19];
    assign e2_a[19] = e2_y[22];
    assign e3_a[19] = e3_y[22];
    assign e_mem_wdata[16] = e1_y[19];
    assign e0_a[20] = mem_wdata[18];
    assign e1_a[20] = e0_y[20];
    assign e2_a[20] = e2_y[22];
    assign e3_a[20] = e3_y[22];
    assign e_mem_wdata[18] = e1_y[20];
    assign e0_a[21] = e0_y[22];
    assign e1_a[21] = e1_y[22];
    assign e2_a[21] = e2_y[22];
    assign e3_a[21] = e3_y[22];
    assign e0_a[22] = e1_y[22];
    assign e1_a[22] = e2_y[22];
    assign e2_a[22] = e3_y[22];
    assign e3_a[22] = mem_rdata_e[1];
    assign mem_rdata_b[1] = e0_y[22];
    assign e0_a[23] = e1_y[23];
    assign e1_a[23] = e2_y[23];
    assign e2_a[23] = e3_y[23];
    assign e3_a[23] = mem_rdata_e[2];
    assign mem_rdata_b[2] = e0_y[23];
    assign e0_a[24] = e1_y[24];
    assign e1_a[24] = e2_y[24];
    assign e2_a[24] = e3_y[24];
    assign e3_a[24] = mem_rdata_e[4];
    assign mem_rdata_b[4] = e0_y[24];
    assign e0_a[25] = e1_y[25];
    assign e1_a[25] = e2_y[25];
    assign e2_a[25] = e3_y[25];
    assign e3_a[25] = mem_rdata_e[14];
    assign mem_rdata_b[14] = e0_y[25];
    assign e0_a[26] = e1_y[26];
    assign e1_a[26] = e2_y[26];
    assign e2_a[26] = e3_y[26];
    assign e3_a[26] = mem_rdata_e[16];
    assign mem_rdata_b[16] = e0_y[26];
    assign e0_a[27] = e1_y[27];
    assign e1_a[27] = e2_y[27];
    assign e2_a[27] = e3_y[27];
    assign e3_a[27] = mem_rdata_e[21];
    assign mem_rdata_b[21] = e0_y[27];
    assign e0_a[28] = e1_y[28];
    assign e1_a[28] = e2_y[28];
    assign e2_a[28] = e3_y[28];
    assign e3_a[28] = mem_rdata_e[22];
    assign mem_rdata_b[22] = e0_y[28];
    assign e0_a[29] = e1_y[29];
    assign e1_a[29] = e2_y[29];
    assign e2_a[29] = mem_rdata_e[8];
    assign e3_a[29] = e3_y[0];
    assign mem_rdata_b[8] = e0_y[29];
    assign e0_a[30] = e1_y[30];
    assign e1_a[30] = e2_y[30];
    assign e2_a[30] = mem_rdata_e[18];
    assign e3_a[30] = e3_y[0];
    assign mem_rdata_b[18] = e0_y[30];
    assign e0_a[31] = e1_y[31];
    assign e1_a[31] = e2_y[31];
    assign e2_a[31] = mem_rdata_e[28];
    assign e3_a[31] = e3_y[0];
    assign mem_rdata_b[28] = e0_y[31];
    assign e0_a[32] = e1_y[32];
    assign e1_a[32] = mem_rdata_e[15];
    assign e2_a[32] = e2_y[0];
    assign e3_a[32] = e3_y[0];
    assign mem_rdata_b[15] = e0_y[32];
    assign e0_a[33] = e1_y[33];
    assign e1_a[33] = mem_rdata_e[20];
    assign e2_a[33] = e2_y[0];
    assign e3_a[33] = e3_y[0];
    assign mem_rdata_b[20] = e0_y[33];
    assign e0_a[34] = e1_y[34];
    assign e1_a[34] = mem_rdata_e[29];
    assign e2_a[34] = e2_y[0];
    assign e3_a[34] = e3_y[0];
    assign mem_rdata_b[29] = e0_y[34];
    assign e0_a[35] = e0_y[0];
    assign e1_a[35] = e1_y[0];
    assign e2_a[35] = e2_y[0];
    assign e3_a[35] = e3_y[0];
    assign e0_a[36] = e0_y[0];
    assign e1_a[36] = e1_y[0];
    assign e2_a[36] = e2_y[0];
    assign e3_a[36] = e3_y[0];
    assign e0_a[37] = e0_y[0];
    assign e1_a[37] = e1_y[0];
    assign e2_a[37] = e2_y[0];
    assign e3_a[37] = e3_y[0];
    assign e0_a[38] = e0_y[0];
    assign e1_a[38] = e1_y[0];
    assign e2_a[38] = e2_y[0];
    assign e3_a[38] = e3_y[0];
    assign e0_a[39] = e0_y[0];
    assign e1_a[39] = e1_y[0];
    assign e2_a[39] = e2_y[0];
    assign e3_a[39] = e3_y[0];

    ntt_repeater u_rw0 (
`ifdef USE_POWER_PINS
        .VPWR(vccd1), .VGND(vssd1),
`endif
        .a(w0_a), .y(w0_y));
    ntt_repeater u_rw1 (
`ifdef USE_POWER_PINS
        .VPWR(vccd1), .VGND(vssd1),
`endif
        .a(w1_a), .y(w1_y));
    ntt_repeater u_rw2 (
`ifdef USE_POWER_PINS
        .VPWR(vccd1), .VGND(vssd1),
`endif
        .a(w2_a), .y(w2_y));
    ntt_repeater u_rw3 (
`ifdef USE_POWER_PINS
        .VPWR(vccd1), .VGND(vssd1),
`endif
        .a(w3_a), .y(w3_y));
    ntt_repeater u_re0 (
`ifdef USE_POWER_PINS
        .VPWR(vccd1), .VGND(vssd1),
`endif
        .a(e0_a), .y(e0_y));
    ntt_repeater u_re1 (
`ifdef USE_POWER_PINS
        .VPWR(vccd1), .VGND(vssd1),
`endif
        .a(e1_a), .y(e1_y));
    ntt_repeater u_re2 (
`ifdef USE_POWER_PINS
        .VPWR(vccd1), .VGND(vssd1),
`endif
        .a(e2_a), .y(e2_y));
    ntt_repeater u_re3 (
`ifdef USE_POWER_PINS
        .VPWR(vccd1), .VGND(vssd1),
`endif
        .a(e3_a), .y(e3_y));

    ntt_wb_bridge u_bridge (
`ifdef USE_POWER_PINS
        .VPWR(vccd1),
        .VGND(vssd1),
`endif
        .wb_clk_i(wb_clk_i),
        .wb_rst_i(wb_rst_i),
        .wbs_stb_i(wbs_stb_i),
        .wbs_cyc_i(wbs_cyc_i),
        .wbs_we_i(wbs_we_i),
        .wbs_sel_i(wbs_sel_i),
        .wbs_dat_i(wbs_dat_i),
        .wbs_adr_i(wbs_adr_i),
        .wbs_ack_o(wbs_ack_o),
        .wbs_dat_o(wbs_dat_o),
        .la_data_out_o(la_data_out_o),
        .io_out_o(io_out_o),
        .io_oeb_o(io_oeb_o),
        .user_irq_o(user_irq_o),
        .start_o(start),
        .engine_rst_n_o(engine_rst_n),
        .op_o(op),
        .slot_a_o(slot_a),
        .slot_b_o(slot_b),
        .slot_c_o(slot_c),
        .mac_init_o(mac_init),
        .mem_we_o(mem_we),
        .mem_re_o(mem_re),
        .mem_target_o(mem_target),
        .mem_slot_o(mem_slot),
        .mem_addr_o(mem_addr),
        .mem_wdata_o(mem_wdata),
        .mem_rdata_i(mem_rdata_b),
        .mem_rvalid_i(mem_rvalid),
        .busy_i(busy_b),
        .done_i(done)
    );

    ntt_engine_256 u_engine (
`ifdef USE_POWER_PINS
`ifdef HARDENED_ENGINE_MACRO
        .VPWR(vccd1),
        .VGND(vssd1),
`else
        .vccd1(vccd1),
        .vssd1(vssd1),
`endif
`endif
        .clk(wb_clk_i),
        .rst_n(e_rst_n),
        .start(e_start),
        .op(e_op),
        .slot_a(e_slot_a),
        .slot_b(e_slot_b),
        .slot_c(e_slot_c),
        .mac_init(e_mac_init),
        .busy(busy_e),
        .done(done),
        .mem_we(e_mem_we),
        .mem_re(e_mem_re),
        .mem_target(e_mem_target),
        .mem_slot(e_mem_slot),
        .mem_addr(e_mem_addr),
        .mem_wdata(e_mem_wdata),
        .mem_rdata(mem_rdata_e),
        .mem_rvalid(mem_rvalid)
    );

endmodule

`default_nettype wire
