###############################################################################
# Created by write_sdc
# Sat Aug 29 13:45:38 2026
###############################################################################
current_design ntt_wb_bridge
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name wb_clk -period 10.0000 [get_ports {wb_clk_i}]
set_clock_transition 0.1500 [get_clocks {wb_clk}]
set_clock_uncertainty 0.2500 wb_clk
set_propagated_clock [get_clocks {wb_clk}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {busy_i}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {done_i}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[0]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[10]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[11]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[12]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[13]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[14]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[15]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[16]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[17]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[18]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[19]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[1]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[20]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[21]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[22]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[23]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[24]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[25]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[26]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[27]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[28]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[29]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[2]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[30]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[31]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[3]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[4]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[5]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[6]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[7]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[8]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rdata_i[9]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_rvalid_i}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wb_rst_i}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[0]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[10]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[11]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[12]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[13]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[14]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[15]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[16]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[17]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[18]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[19]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[1]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[20]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[21]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[22]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[23]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[24]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[25]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[26]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[27]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[28]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[29]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[2]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[30]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[31]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[3]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[4]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[5]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[6]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[7]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[8]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_adr_i[9]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_cyc_i}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[0]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[10]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[11]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[12]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[13]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[14]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[15]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[16]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[17]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[18]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[19]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[1]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[20]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[21]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[22]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[23]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[24]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[25]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[26]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[27]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[28]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[29]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[2]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[30]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[31]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[3]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[4]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[5]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[6]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[7]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[8]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_i[9]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_sel_i[0]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_sel_i[1]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_sel_i[2]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_sel_i[3]}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_stb_i}]
set_input_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_we_i}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {VGND}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {VPWR}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {engine_rst_n_o}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[10]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[11]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[12]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[13]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[14]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[15]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[16]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[17]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[18]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[19]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[20]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[21]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[22]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[23]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[24]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[25]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[26]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[27]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[28]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[29]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[30]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[31]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[32]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[33]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[34]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[35]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[36]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[37]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[3]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[4]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[5]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[6]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[7]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[8]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_oeb_o[9]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[10]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[11]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[12]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[13]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[14]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[15]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[16]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[17]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[18]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[19]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[20]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[21]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[22]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[23]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[24]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[25]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[26]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[27]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[28]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[29]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[30]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[31]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[32]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[33]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[34]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[35]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[36]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[37]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[3]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[4]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[5]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[6]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[7]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[8]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {io_out_o[9]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[100]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[101]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[102]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[103]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[104]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[105]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[106]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[107]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[108]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[109]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[10]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[110]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[111]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[112]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[113]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[114]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[115]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[116]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[117]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[118]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[119]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[11]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[120]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[121]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[122]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[123]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[124]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[125]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[126]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[127]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[12]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[13]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[14]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[15]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[16]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[17]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[18]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[19]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[20]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[21]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[22]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[23]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[24]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[25]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[26]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[27]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[28]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[29]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[30]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[31]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[32]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[33]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[34]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[35]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[36]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[37]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[38]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[39]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[3]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[40]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[41]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[42]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[43]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[44]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[45]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[46]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[47]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[48]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[49]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[4]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[50]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[51]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[52]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[53]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[54]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[55]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[56]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[57]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[58]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[59]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[5]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[60]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[61]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[62]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[63]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[64]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[65]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[66]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[67]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[68]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[69]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[6]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[70]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[71]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[72]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[73]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[74]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[75]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[76]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[77]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[78]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[79]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[7]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[80]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[81]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[82]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[83]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[84]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[85]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[86]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[87]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[88]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[89]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[8]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[90]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[91]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[92]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[93]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[94]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[95]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[96]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[97]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[98]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[99]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {la_data_out_o[9]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mac_init_o}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_addr_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_addr_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_addr_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_addr_o[3]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_addr_o[4]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_addr_o[5]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_addr_o[6]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_addr_o[7]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_addr_o[8]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_re_o}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_slot_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_slot_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_target_o}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[10]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[11]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[12]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[13]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[14]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[15]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[16]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[17]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[18]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[19]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[20]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[21]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[22]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[23]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[24]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[25]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[26]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[27]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[28]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[29]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[30]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[31]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[3]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[4]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[5]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[6]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[7]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[8]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_wdata_o[9]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {mem_we_o}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {op_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {op_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {op_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {slot_a_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {slot_a_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {slot_b_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {slot_b_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {slot_c_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {slot_c_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {start_o}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {user_irq_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {user_irq_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {user_irq_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_ack_o}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[10]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[11]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[12]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[13]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[14]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[15]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[16]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[17]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[18]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[19]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[20]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[21]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[22]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[23]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[24]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[25]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[26]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[27]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[28]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[29]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[30]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[31]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[3]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[4]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[5]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[6]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[7]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[8]}]
set_output_delay 2.0000 -clock [get_clocks {wb_clk}] -add_delay [get_ports {wbs_dat_o[9]}]
set_false_path\
    -from [get_ports {wb_rst_i}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.1000 [get_ports {VGND}]
set_load -pin_load 0.1000 [get_ports {VPWR}]
set_load -pin_load 0.1000 [get_ports {engine_rst_n_o}]
set_load -pin_load 0.1000 [get_ports {mac_init_o}]
set_load -pin_load 0.1000 [get_ports {mem_re_o}]
set_load -pin_load 0.1000 [get_ports {mem_target_o}]
set_load -pin_load 0.1000 [get_ports {mem_we_o}]
set_load -pin_load 0.1000 [get_ports {start_o}]
set_load -pin_load 0.1000 [get_ports {wbs_ack_o}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[37]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[36]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[35]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[34]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[33]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[32]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[31]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[30]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[29]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[28]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[27]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[26]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[25]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[24]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[23]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[22]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[21]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[20]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[19]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[18]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[17]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[16]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[15]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[14]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[13]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[12]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[11]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[10]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[9]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[8]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[7]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[6]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[5]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[4]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[3]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[2]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[1]}]
set_load -pin_load 0.1000 [get_ports {io_oeb_o[0]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[37]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[36]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[35]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[34]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[33]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[32]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[31]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[30]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[29]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[28]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[27]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[26]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[25]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[24]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[23]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[22]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[21]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[20]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[19]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[18]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[17]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[16]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[15]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[14]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[13]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[12]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[11]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[10]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[9]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[8]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[7]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[6]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[5]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[4]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[3]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[2]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[1]}]
set_load -pin_load 0.1000 [get_ports {io_out_o[0]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[127]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[126]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[125]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[124]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[123]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[122]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[121]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[120]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[119]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[118]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[117]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[116]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[115]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[114]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[113]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[112]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[111]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[110]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[109]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[108]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[107]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[106]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[105]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[104]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[103]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[102]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[101]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[100]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[99]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[98]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[97]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[96]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[95]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[94]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[93]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[92]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[91]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[90]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[89]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[88]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[87]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[86]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[85]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[84]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[83]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[82]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[81]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[80]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[79]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[78]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[77]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[76]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[75]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[74]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[73]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[72]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[71]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[70]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[69]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[68]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[67]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[66]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[65]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[64]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[63]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[62]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[61]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[60]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[59]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[58]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[57]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[56]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[55]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[54]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[53]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[52]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[51]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[50]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[49]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[48]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[47]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[46]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[45]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[44]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[43]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[42]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[41]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[40]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[39]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[38]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[37]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[36]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[35]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[34]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[33]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[32]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[31]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[30]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[29]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[28]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[27]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[26]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[25]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[24]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[23]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[22]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[21]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[20]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[19]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[18]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[17]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[16]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[15]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[14]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[13]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[12]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[11]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[10]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[9]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[8]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[7]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[6]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[5]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[4]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[3]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[2]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[1]}]
set_load -pin_load 0.1000 [get_ports {la_data_out_o[0]}]
set_load -pin_load 0.1000 [get_ports {mem_addr_o[8]}]
set_load -pin_load 0.1000 [get_ports {mem_addr_o[7]}]
set_load -pin_load 0.1000 [get_ports {mem_addr_o[6]}]
set_load -pin_load 0.1000 [get_ports {mem_addr_o[5]}]
set_load -pin_load 0.1000 [get_ports {mem_addr_o[4]}]
set_load -pin_load 0.1000 [get_ports {mem_addr_o[3]}]
set_load -pin_load 0.1000 [get_ports {mem_addr_o[2]}]
set_load -pin_load 0.1000 [get_ports {mem_addr_o[1]}]
set_load -pin_load 0.1000 [get_ports {mem_addr_o[0]}]
set_load -pin_load 0.1000 [get_ports {mem_slot_o[1]}]
set_load -pin_load 0.1000 [get_ports {mem_slot_o[0]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[31]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[30]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[29]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[28]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[27]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[26]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[25]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[24]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[23]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[22]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[21]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[20]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[19]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[18]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[17]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[16]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[15]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[14]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[13]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[12]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[11]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[10]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[9]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[8]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[7]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[6]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[5]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[4]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[3]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[2]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[1]}]
set_load -pin_load 0.1000 [get_ports {mem_wdata_o[0]}]
set_load -pin_load 0.1000 [get_ports {op_o[2]}]
set_load -pin_load 0.1000 [get_ports {op_o[1]}]
set_load -pin_load 0.1000 [get_ports {op_o[0]}]
set_load -pin_load 0.1000 [get_ports {slot_a_o[1]}]
set_load -pin_load 0.1000 [get_ports {slot_a_o[0]}]
set_load -pin_load 0.1000 [get_ports {slot_b_o[1]}]
set_load -pin_load 0.1000 [get_ports {slot_b_o[0]}]
set_load -pin_load 0.1000 [get_ports {slot_c_o[1]}]
set_load -pin_load 0.1000 [get_ports {slot_c_o[0]}]
set_load -pin_load 0.1000 [get_ports {user_irq_o[2]}]
set_load -pin_load 0.1000 [get_ports {user_irq_o[1]}]
set_load -pin_load 0.1000 [get_ports {user_irq_o[0]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[31]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[30]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[29]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[28]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[27]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[26]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[25]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[24]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[23]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[22]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[21]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[20]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[19]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[18]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[17]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[16]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[15]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[14]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[13]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[12]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[11]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[10]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[9]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[8]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[7]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[6]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[5]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[4]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[3]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[2]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[1]}]
set_load -pin_load 0.1000 [get_ports {wbs_dat_o[0]}]
set_input_transition 0.1500 [get_ports {busy_i}]
set_input_transition 0.1500 [get_ports {done_i}]
set_input_transition 0.1500 [get_ports {mem_rvalid_i}]
set_input_transition 0.1500 [get_ports {wb_rst_i}]
set_input_transition 0.1500 [get_ports {wbs_cyc_i}]
set_input_transition 0.1500 [get_ports {wbs_stb_i}]
set_input_transition 0.1500 [get_ports {wbs_we_i}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[31]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[30]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[29]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[28]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[27]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[26]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[25]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[24]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[23]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[22]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[21]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[20]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[19]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[18]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[17]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[16]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[15]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[14]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[13]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[12]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[11]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[10]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[9]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[8]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[7]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[6]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[5]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[4]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[3]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[2]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[1]}]
set_input_transition 0.1500 [get_ports {mem_rdata_i[0]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[31]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[30]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[29]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[28]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[27]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[26]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[25]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[24]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[23]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[22]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[21]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[20]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[19]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[18]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[17]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[16]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[15]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[14]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[13]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[12]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[11]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[10]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[9]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[8]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[7]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[6]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[5]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[4]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[3]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[2]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[1]}]
set_input_transition 0.1500 [get_ports {wbs_adr_i[0]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[31]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[30]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[29]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[28]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[27]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[26]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[25]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[24]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[23]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[22]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[21]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[20]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[19]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[18]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[17]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[16]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[15]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[14]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[13]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[12]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[11]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[10]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[9]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[8]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[7]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[6]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[5]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[4]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[3]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[2]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[1]}]
set_input_transition 0.1500 [get_ports {wbs_dat_i[0]}]
set_input_transition 0.1500 [get_ports {wbs_sel_i[3]}]
set_input_transition 0.1500 [get_ports {wbs_sel_i[2]}]
set_input_transition 0.1500 [get_ports {wbs_sel_i[1]}]
set_input_transition 0.1500 [get_ports {wbs_sel_i[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.5000 [current_design]
set_max_fanout 128.0000 [current_design]
