###############################################################################
# Created by write_sdc
# Fri Sep 11 02:06:44 2026
###############################################################################
current_design ntt_repeater
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name virt -period 10.0000 
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {VGND}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {VPWR}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[0]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[10]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[11]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[12]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[13]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[14]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[15]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[16]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[17]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[18]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[19]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[1]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[20]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[21]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[22]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[23]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[24]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[25]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[26]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[27]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[28]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[29]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[2]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[30]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[31]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[32]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[33]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[34]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[35]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[36]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[37]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[38]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[39]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[3]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[4]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[5]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[6]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[7]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[8]}]
set_input_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {a[9]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {VGND}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {VPWR}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[0]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[10]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[11]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[12]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[13]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[14]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[15]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[16]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[17]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[18]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[19]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[1]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[20]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[21]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[22]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[23]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[24]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[25]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[26]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[27]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[28]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[29]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[2]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[30]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[31]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[32]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[33]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[34]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[35]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[36]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[37]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[38]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[39]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[3]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[4]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[5]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[6]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[7]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[8]}]
set_output_delay 1.0000 -clock [get_clocks {virt}] -add_delay [get_ports {y[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 1.2000 [get_ports {VGND}]
set_load -pin_load 1.2000 [get_ports {VPWR}]
set_load -pin_load 1.2000 [get_ports {y[39]}]
set_load -pin_load 1.2000 [get_ports {y[38]}]
set_load -pin_load 1.2000 [get_ports {y[37]}]
set_load -pin_load 1.2000 [get_ports {y[36]}]
set_load -pin_load 1.2000 [get_ports {y[35]}]
set_load -pin_load 1.2000 [get_ports {y[34]}]
set_load -pin_load 1.2000 [get_ports {y[33]}]
set_load -pin_load 1.2000 [get_ports {y[32]}]
set_load -pin_load 1.2000 [get_ports {y[31]}]
set_load -pin_load 1.2000 [get_ports {y[30]}]
set_load -pin_load 1.2000 [get_ports {y[29]}]
set_load -pin_load 1.2000 [get_ports {y[28]}]
set_load -pin_load 1.2000 [get_ports {y[27]}]
set_load -pin_load 1.2000 [get_ports {y[26]}]
set_load -pin_load 1.2000 [get_ports {y[25]}]
set_load -pin_load 1.2000 [get_ports {y[24]}]
set_load -pin_load 1.2000 [get_ports {y[23]}]
set_load -pin_load 1.2000 [get_ports {y[22]}]
set_load -pin_load 1.2000 [get_ports {y[21]}]
set_load -pin_load 1.2000 [get_ports {y[20]}]
set_load -pin_load 1.2000 [get_ports {y[19]}]
set_load -pin_load 1.2000 [get_ports {y[18]}]
set_load -pin_load 1.2000 [get_ports {y[17]}]
set_load -pin_load 1.2000 [get_ports {y[16]}]
set_load -pin_load 1.2000 [get_ports {y[15]}]
set_load -pin_load 1.2000 [get_ports {y[14]}]
set_load -pin_load 1.2000 [get_ports {y[13]}]
set_load -pin_load 1.2000 [get_ports {y[12]}]
set_load -pin_load 1.2000 [get_ports {y[11]}]
set_load -pin_load 1.2000 [get_ports {y[10]}]
set_load -pin_load 1.2000 [get_ports {y[9]}]
set_load -pin_load 1.2000 [get_ports {y[8]}]
set_load -pin_load 1.2000 [get_ports {y[7]}]
set_load -pin_load 1.2000 [get_ports {y[6]}]
set_load -pin_load 1.2000 [get_ports {y[5]}]
set_load -pin_load 1.2000 [get_ports {y[4]}]
set_load -pin_load 1.2000 [get_ports {y[3]}]
set_load -pin_load 1.2000 [get_ports {y[2]}]
set_load -pin_load 1.2000 [get_ports {y[1]}]
set_load -pin_load 1.2000 [get_ports {y[0]}]
set_input_transition 1.0000 [get_ports {VGND}]
set_input_transition 1.0000 [get_ports {VPWR}]
set_input_transition 1.0000 [get_ports {a[39]}]
set_input_transition 1.0000 [get_ports {a[38]}]
set_input_transition 1.0000 [get_ports {a[37]}]
set_input_transition 1.0000 [get_ports {a[36]}]
set_input_transition 1.0000 [get_ports {a[35]}]
set_input_transition 1.0000 [get_ports {a[34]}]
set_input_transition 1.0000 [get_ports {a[33]}]
set_input_transition 1.0000 [get_ports {a[32]}]
set_input_transition 1.0000 [get_ports {a[31]}]
set_input_transition 1.0000 [get_ports {a[30]}]
set_input_transition 1.0000 [get_ports {a[29]}]
set_input_transition 1.0000 [get_ports {a[28]}]
set_input_transition 1.0000 [get_ports {a[27]}]
set_input_transition 1.0000 [get_ports {a[26]}]
set_input_transition 1.0000 [get_ports {a[25]}]
set_input_transition 1.0000 [get_ports {a[24]}]
set_input_transition 1.0000 [get_ports {a[23]}]
set_input_transition 1.0000 [get_ports {a[22]}]
set_input_transition 1.0000 [get_ports {a[21]}]
set_input_transition 1.0000 [get_ports {a[20]}]
set_input_transition 1.0000 [get_ports {a[19]}]
set_input_transition 1.0000 [get_ports {a[18]}]
set_input_transition 1.0000 [get_ports {a[17]}]
set_input_transition 1.0000 [get_ports {a[16]}]
set_input_transition 1.0000 [get_ports {a[15]}]
set_input_transition 1.0000 [get_ports {a[14]}]
set_input_transition 1.0000 [get_ports {a[13]}]
set_input_transition 1.0000 [get_ports {a[12]}]
set_input_transition 1.0000 [get_ports {a[11]}]
set_input_transition 1.0000 [get_ports {a[10]}]
set_input_transition 1.0000 [get_ports {a[9]}]
set_input_transition 1.0000 [get_ports {a[8]}]
set_input_transition 1.0000 [get_ports {a[7]}]
set_input_transition 1.0000 [get_ports {a[6]}]
set_input_transition 1.0000 [get_ports {a[5]}]
set_input_transition 1.0000 [get_ports {a[4]}]
set_input_transition 1.0000 [get_ports {a[3]}]
set_input_transition 1.0000 [get_ports {a[2]}]
set_input_transition 1.0000 [get_ports {a[1]}]
set_input_transition 1.0000 [get_ports {a[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.5000 [current_design]
set_max_fanout 128.0000 [current_design]
