###############################################################################
# Created by write_sdc
# Sat Aug 29 01:22:27 2026
###############################################################################
current_design ntt_engine_256
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mac_init}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_re}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_slot[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_slot[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_target}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_we}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {op[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {op[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {op[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {slot_a[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {slot_a[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {slot_b[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {slot_b[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {slot_c[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {slot_c[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {start}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {busy}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {done}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rdata[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_rvalid}]
set_false_path\
    -from [get_ports {rst_n}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.1000 [get_ports {busy}]
set_load -pin_load 0.1000 [get_ports {done}]
set_load -pin_load 0.1000 [get_ports {mem_rvalid}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[31]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[30]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[29]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[28]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[27]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[26]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[25]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[24]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[23]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[22]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[21]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[20]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[19]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[18]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[17]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[16]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[15]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[14]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[13]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[12]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[11]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[10]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[9]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[8]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[7]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[6]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[5]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[4]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[3]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[2]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[1]}]
set_load -pin_load 0.1000 [get_ports {mem_rdata[0]}]
set_input_transition 0.1500 [get_ports {mac_init}]
set_input_transition 0.1500 [get_ports {mem_re}]
set_input_transition 0.1500 [get_ports {mem_target}]
set_input_transition 0.1500 [get_ports {mem_we}]
set_input_transition 0.1500 [get_ports {rst_n}]
set_input_transition 0.1500 [get_ports {start}]
set_input_transition 0.1500 [get_ports {mem_addr[8]}]
set_input_transition 0.1500 [get_ports {mem_addr[7]}]
set_input_transition 0.1500 [get_ports {mem_addr[6]}]
set_input_transition 0.1500 [get_ports {mem_addr[5]}]
set_input_transition 0.1500 [get_ports {mem_addr[4]}]
set_input_transition 0.1500 [get_ports {mem_addr[3]}]
set_input_transition 0.1500 [get_ports {mem_addr[2]}]
set_input_transition 0.1500 [get_ports {mem_addr[1]}]
set_input_transition 0.1500 [get_ports {mem_addr[0]}]
set_input_transition 0.1500 [get_ports {mem_slot[1]}]
set_input_transition 0.1500 [get_ports {mem_slot[0]}]
set_input_transition 0.1500 [get_ports {mem_wdata[31]}]
set_input_transition 0.1500 [get_ports {mem_wdata[30]}]
set_input_transition 0.1500 [get_ports {mem_wdata[29]}]
set_input_transition 0.1500 [get_ports {mem_wdata[28]}]
set_input_transition 0.1500 [get_ports {mem_wdata[27]}]
set_input_transition 0.1500 [get_ports {mem_wdata[26]}]
set_input_transition 0.1500 [get_ports {mem_wdata[25]}]
set_input_transition 0.1500 [get_ports {mem_wdata[24]}]
set_input_transition 0.1500 [get_ports {mem_wdata[23]}]
set_input_transition 0.1500 [get_ports {mem_wdata[22]}]
set_input_transition 0.1500 [get_ports {mem_wdata[21]}]
set_input_transition 0.1500 [get_ports {mem_wdata[20]}]
set_input_transition 0.1500 [get_ports {mem_wdata[19]}]
set_input_transition 0.1500 [get_ports {mem_wdata[18]}]
set_input_transition 0.1500 [get_ports {mem_wdata[17]}]
set_input_transition 0.1500 [get_ports {mem_wdata[16]}]
set_input_transition 0.1500 [get_ports {mem_wdata[15]}]
set_input_transition 0.1500 [get_ports {mem_wdata[14]}]
set_input_transition 0.1500 [get_ports {mem_wdata[13]}]
set_input_transition 0.1500 [get_ports {mem_wdata[12]}]
set_input_transition 0.1500 [get_ports {mem_wdata[11]}]
set_input_transition 0.1500 [get_ports {mem_wdata[10]}]
set_input_transition 0.1500 [get_ports {mem_wdata[9]}]
set_input_transition 0.1500 [get_ports {mem_wdata[8]}]
set_input_transition 0.1500 [get_ports {mem_wdata[7]}]
set_input_transition 0.1500 [get_ports {mem_wdata[6]}]
set_input_transition 0.1500 [get_ports {mem_wdata[5]}]
set_input_transition 0.1500 [get_ports {mem_wdata[4]}]
set_input_transition 0.1500 [get_ports {mem_wdata[3]}]
set_input_transition 0.1500 [get_ports {mem_wdata[2]}]
set_input_transition 0.1500 [get_ports {mem_wdata[1]}]
set_input_transition 0.1500 [get_ports {mem_wdata[0]}]
set_input_transition 0.1500 [get_ports {op[2]}]
set_input_transition 0.1500 [get_ports {op[1]}]
set_input_transition 0.1500 [get_ports {op[0]}]
set_input_transition 0.1500 [get_ports {slot_a[1]}]
set_input_transition 0.1500 [get_ports {slot_a[0]}]
set_input_transition 0.1500 [get_ports {slot_b[1]}]
set_input_transition 0.1500 [get_ports {slot_b[0]}]
set_input_transition 0.1500 [get_ports {slot_c[1]}]
set_input_transition 0.1500 [get_ports {slot_c[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 6.0000 [current_design]
