#!/usr/bin/env python3
"""Generate verilog/rtl/ntt.v: bridge + engine + two 3-stage ntt_repeater chains.

Every engine<->bridge signal whose engine pin is on the W, E or N edge is routed
through a repeater chain (west chain for W pins and N pins with x < NSPLIT_X,
east chain for the rest). S-edge pins connect directly. Entry/exit stage for
side pins is the instance nearest the pin; N pins use the top instance.
Bits [0:NUP) are "up" (bridge->engine, a on #S, y on #N);
bits [NUP:NBITS) are "down" (engine->bridge, a on #N, y on #S).
Unused inputs are tied to an always-driven output on the same edge of the
same instance (y[NUP] for up-side spares, y[0] for down-side spares).
"""
import re, sys, collections

LEF, OUT = 'lef/ntt_engine_256.lef', 'verilog/rtl/ntt.v'
NBITS, NUP = 40, 22
NDN = NBITS - NUP
ENG_X, ENG_Y, ENG_SZ = 320, 900, 2400
INST_Y = [536, 1256, 2156, 3056]     # from openlane/user_project_wrapper/macro.cfg
INST_H = 180
CENTERS = [y + INST_H / 2 for y in INST_Y]
NST = len(INST_Y)
NSPLIT_X = 1200                      # engine-relative x that splits N pins between chains

# engine port -> (width, direction); 'in' = bridge -> engine
PORTS = collections.OrderedDict([
    ('rst_n', (1, 'in')), ('start', (1, 'in')), ('op', (3, 'in')),
    ('slot_a', (2, 'in')), ('slot_b', (2, 'in')), ('slot_c', (2, 'in')),
    ('mac_init', (1, 'in')), ('mem_we', (1, 'in')), ('mem_re', (1, 'in')),
    ('mem_target', (1, 'in')), ('mem_slot', (2, 'in')), ('mem_addr', (9, 'in')),
    ('mem_wdata', (32, 'in')),
    ('busy', (1, 'out')), ('done', (1, 'out')), ('mem_rdata', (32, 'out')),
    ('mem_rvalid', (1, 'out')),
])
BRIDGE_PORT = {'rst_n': 'engine_rst_n_o'}   # bridge port name for engine port (default name+_o / name+_i)

def bnet(p, i):   # bridge-side net
    base = {'rst_n': 'engine_rst_n', 'busy': 'busy_b', 'mem_rdata': 'mem_rdata_b'}.get(p, p)
    return f'{base}[{i}]' if PORTS[p][0] > 1 else base
def enet(p, i):   # engine-side net
    base = {'busy': 'busy_e', 'mem_rdata': 'mem_rdata_e'}.get(p, 'e_' + p if PORTS[p][1] == 'in' else p)
    return f'{base}[{i}]' if PORTS[p][0] > 1 else base

# ---- parse engine LEF pins ----
lef = open(LEF).read()
pins = {}
for m in re.finditer(r'PIN (\S+)\s.*?RECT ([\d.]+) ([\d.]+) ([\d.]+) ([\d.]+)', lef, re.S):
    pins[m.group(1)] = tuple(map(float, m.groups()[1:]))

def edge(r):
    x1, y1, x2, y2 = r
    if x1 < 5: return 'W'
    if x2 > ENG_SZ - 5: return 'E'
    if y1 < 5: return 'S'
    if y2 > ENG_SZ - 5: return 'N'
    raise SystemExit(f'pin not on boundary: {r}')

# ---- classify every signal bit ----
sig = []   # dicts: port, idx, dir, edge, chain, stage (None = direct)
for p, (w, d) in PORTS.items():
    for i in range(w):
        name = f'{p}[{i}]' if w > 1 else p
        if name not in pins: raise SystemExit(f'missing pin {name} in LEF')
        x1, y1, x2, y2 = pins[name]; e = edge(pins[name])
        if e == 'S':
            sig.append(dict(port=p, idx=i, dir=d, edge=e, chain=None, stage=None)); continue
        if e == 'N': chain = 'w' if x1 < NSPLIT_X else 'e'; stage = NST - 1
        else:
            chain = 'w' if e == 'W' else 'e'
            yabs = y1 + ENG_Y
            stage = min(range(NST), key=lambda k: abs(yabs - CENTERS[k]))
        sig.append(dict(port=p, idx=i, dir=d, edge=e, chain=chain, stage=stage))

# ---- assign bits per chain: stage-2 signals first so bit 0 / bit NUP are always driven ----
bits = {}   # (chain, bit) -> sig
for chain in ('w', 'e'):
    up = sorted([s for s in sig if s['chain'] == chain and s['dir'] == 'in'], key=lambda s: -s['stage'])
    dn = sorted([s for s in sig if s['chain'] == chain and s['dir'] == 'out'], key=lambda s: -s['stage'])
    if len(up) > NUP or len(dn) > NDN:
        raise SystemExit(f'chain {chain}: {len(up)} up / {len(dn)} down exceeds {NUP}/{NDN}')
    if not up or up[0]['stage'] != NST - 1 or not dn or dn[0]['stage'] != NST - 1:
        raise SystemExit(f'chain {chain}: need a stage-2 signal in both directions for tie-offs')
    for k, s in enumerate(up): bits[(chain, k)] = s; s['bit'] = k
    for k, s in enumerate(dn): bits[(chain, NUP + k)] = s; s['bit'] = NUP + k
    print(f'chain {chain}: {len(up)} up, {len(dn)} down', file=sys.stderr)

# ---- emit ----
L = []
A = L.append
A('// SPDX-FileCopyrightText: 2020 Efabless Corporation')
A('// SPDX-License-Identifier: Apache-2.0')
A('// GENERATED by scripts/gen_ntt_v.py from lef/ntt_engine_256.lef. Do not hand-edit.')
A('')
A('`default_nettype none')
A('')
A('// Physical integration shell around hardened macros. The wrapper flow flattens')
A('// this shell, leaving u_bridge, u_engine and eight ntt_repeater instances as hard')
A('// macros inside user_project_wrapper. See scripts/gen_ntt_v.py for the scheme.')
A('//')
A('// Signal map (chain/bit/direction/entry-or-exit stage):')
for chain in ('w', 'e'):
    for k in range(NBITS):
        s = bits.get((chain, k))
        if s:
            name = f"{s['port']}[{s['idx']}]" if PORTS[s['port']][0] > 1 else s['port']
            A(f"//   {chain}{k:2d} {'up  ' if s['dir']=='in' else 'down'} stage {s['stage']}  {name} ({s['edge']} edge)")
        else:
            A(f"//   {chain}{k:2d} spare")
A('module ntt (')
A('`ifdef USE_POWER_PINS')
A('    inout  wire        vccd1,')
A('    inout  wire        vssd1,')
A('`endif')
A('''    input  wire        wb_clk_i,
    input  wire        wb_rst_i,
    input  wire        wbs_stb_i,
    input  wire        wbs_cyc_i,
    input  wire        wbs_we_i,
    input  wire [3:0]  wbs_sel_i,
    input  wire [31:0] wbs_dat_i,
    input  wire [31:0] wbs_adr_i,
    output wire        wbs_ack_o,
    output wire [31:0] wbs_dat_o,
    output wire [127:0] la_data_out_o,
    output wire [37:0]  io_out_o,
    output wire [37:0]  io_oeb_o,
    output wire [2:0]   user_irq_o,
    output wire        busy_o,
    output wire        done_o,
    output wire        ext_rvalid_o
);
''')
# nets
for p, (w, d) in PORTS.items():
    dim = f'[{w-1}:0] ' if w > 1 else ''
    if d == 'in':
        A(f'    wire {dim}{bnet(p,0).split("[")[0]};')
        A(f'    wire {dim}{enet(p,0).split("[")[0]};')
    else:
        A(f'    wire {dim}{enet(p,0).split("[")[0]};')
        if bnet(p,0) != enet(p,0): A(f'    wire {dim}{bnet(p,0).split("[")[0]};')
for chain in ('w', 'e'):
    for st in range(NST):
        A(f'    wire [{NBITS-1}:0] {chain}{st}_a, {chain}{st}_y;')
A('')
A('    assign busy_o       = busy_b;')
A('    assign done_o       = done;')
A('    assign ext_rvalid_o = mem_rvalid;')
A('')
# direct connections
A('    // ---- direct (south-edge) connections ----')
for s in sig:
    if s['chain'] is None:
        if s['dir'] == 'in': A(f"    assign {enet(s['port'],s['idx'])} = {bnet(s['port'],s['idx'])};")
        else:                A(f"    assign {bnet(s['port'],s['idx'])} = {enet(s['port'],s['idx'])};")
A('')
# chains
for chain in ('w', 'e'):
    A(f"    // ---- {'west' if chain=='w' else 'east'} chain ----")
    for k in range(NBITS):
        s = bits.get((chain, k))
        up_side = k < NUP
        for st in range(NST):
            a = f'{chain}{st}_a[{k}]'
            if s is None:
                src = f'{chain}{st}_y[{NUP}]' if up_side else f'{chain}{st}_y[0]'
            elif s['dir'] == 'in':                       # up: bridge -> r0 -> ... -> r_stage -> engine
                if st == 0: src = bnet(s['port'], s['idx'])
                elif st <= s['stage']: src = f'{chain}{st-1}_y[{k}]'
                else: src = f'{chain}{st}_y[{NUP}]'
            else:                                        # down: engine -> r_stage -> ... -> r0 -> bridge
                if st == s['stage']: src = enet(s['port'], s['idx'])
                elif st < s['stage']: src = f'{chain}{st+1}_y[{k}]'
                else: src = f'{chain}{st}_y[0]'
            A(f'    assign {a} = {src};')
        if s is not None:
            if s['dir'] == 'in': A(f"    assign {enet(s['port'],s['idx'])} = {chain}{s['stage']}_y[{k}];")
            else:                A(f"    assign {bnet(s['port'],s['idx'])} = {chain}0_y[{k}];")
    A('')
# instances
for chain in ('w', 'e'):
    for st in range(NST):
        A(f'    ntt_repeater u_r{chain}{st} (')
        A('`ifdef USE_POWER_PINS')
        A('        .VPWR(vccd1), .VGND(vssd1),')
        A('`endif')
        A(f'        .a({chain}{st}_a), .y({chain}{st}_y));')
A('')
A('''    ntt_wb_bridge u_bridge (
`ifdef USE_POWER_PINS
        .VPWR(vccd1),
        .VGND(vssd1),
`endif
        .wb_clk_i(wb_clk_i),
        .wb_rst_i(wb_rst_i),
        .wbs_stb_i(wbs_stb_i),
        .wbs_cyc_i(wbs_cyc_i),
        .wbs_we_i(wbs_we_i),
        .wbs_sel_i(wbs_sel_i),
        .wbs_dat_i(wbs_dat_i),
        .wbs_adr_i(wbs_adr_i),
        .wbs_ack_o(wbs_ack_o),
        .wbs_dat_o(wbs_dat_o),
        .la_data_out_o(la_data_out_o),
        .io_out_o(io_out_o),
        .io_oeb_o(io_oeb_o),
        .user_irq_o(user_irq_o),
        .start_o(start),
        .engine_rst_n_o(engine_rst_n),
        .op_o(op),
        .slot_a_o(slot_a),
        .slot_b_o(slot_b),
        .slot_c_o(slot_c),
        .mac_init_o(mac_init),
        .mem_we_o(mem_we),
        .mem_re_o(mem_re),
        .mem_target_o(mem_target),
        .mem_slot_o(mem_slot),
        .mem_addr_o(mem_addr),
        .mem_wdata_o(mem_wdata),
        .mem_rdata_i(mem_rdata_b),
        .mem_rvalid_i(mem_rvalid),
        .busy_i(busy_b),
        .done_i(done)
    );

    ntt_engine_256 u_engine (
`ifdef USE_POWER_PINS
`ifdef HARDENED_ENGINE_MACRO
        .VPWR(vccd1),
        .VGND(vssd1),
`else
        .vccd1(vccd1),
        .vssd1(vssd1),
`endif
`endif
        .clk(wb_clk_i),
        .rst_n(e_rst_n),
        .start(e_start),
        .op(e_op),
        .slot_a(e_slot_a),
        .slot_b(e_slot_b),
        .slot_c(e_slot_c),
        .mac_init(e_mac_init),
        .busy(busy_e),
        .done(done),
        .mem_we(e_mem_we),
        .mem_re(e_mem_re),
        .mem_target(e_mem_target),
        .mem_slot(e_mem_slot),
        .mem_addr(e_mem_addr),
        .mem_wdata(e_mem_wdata),
        .mem_rdata(mem_rdata_e),
        .mem_rvalid(mem_rvalid)
    );

endmodule

`default_nettype wire''')
open(OUT, 'w').write('\n'.join(L) + '\n')
n_rep = sum(1 for s in sig if s['chain']); n_dir = len(sig) - n_rep
print(f'wrote {OUT}: {n_rep} repeated, {n_dir} direct', file=sys.stderr)
