-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ntt_kernel_ntt_kernel_Pipeline_FLATTENED_BUTTERFLY_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    half_n : IN STD_LOGIC_VECTOR (30 downto 0);
    sub53 : IN STD_LOGIC_VECTOR (11 downto 0);
    stage : IN STD_LOGIC_VECTOR (31 downto 0);
    stage_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_29 : IN STD_LOGIC_VECTOR (11 downto 0);
    empty : IN STD_LOGIC_VECTOR (11 downto 0);
    local_twiddles_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    local_twiddles_ce0 : OUT STD_LOGIC;
    local_twiddles_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    ping_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ping_ce0 : OUT STD_LOGIC;
    ping_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    ping_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ping_ce1 : OUT STD_LOGIC;
    ping_we1 : OUT STD_LOGIC;
    ping_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ping_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    pong_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    pong_ce0 : OUT STD_LOGIC;
    pong_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    pong_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    pong_ce1 : OUT STD_LOGIC;
    pong_we1 : OUT STD_LOGIC;
    pong_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    pong_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    use_ping_as_input : IN STD_LOGIC_VECTOR (0 downto 0);
    q_inv : IN STD_LOGIC_VECTOR (31 downto 0);
    conv5_i : IN STD_LOGIC_VECTOR (31 downto 0);
    q : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of ntt_kernel_ntt_kernel_Pipeline_FLATTENED_BUTTERFLY_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_pp0_stage8 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_pp0_stage9 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_pp0_stage10 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_pp0_stage11 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_pp0_stage12 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv30_1 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln126_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage12 : signal is "none";
    signal ap_block_pp0_stage12_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal use_ping_as_input_read_reg_494 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv5_i_cast_fu_235_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal conv5_i_cast_reg_510 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln126_reg_515 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_271_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal j_reg_519 : STD_LOGIC_VECTOR (11 downto 0);
    signal lshr_ln131_fu_277_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln131_reg_525 : STD_LOGIC_VECTOR (31 downto 0);
    signal twiddle_reg_535 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ping_addr_reg_540 : STD_LOGIC_VECTOR (11 downto 0);
    signal ping_addr_1_reg_545 : STD_LOGIC_VECTOR (11 downto 0);
    signal pong_addr_reg_551 : STD_LOGIC_VECTOR (11 downto 0);
    signal pong_addr_1_reg_556 : STD_LOGIC_VECTOR (11 downto 0);
    signal u_reg_562 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal u_1_reg_567 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln24_fu_341_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln24_1_fu_346_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_227_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ab_reg_582 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal zext_ln33_fu_355_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp0_stage8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage8 : signal is "none";
    signal ap_block_pp0_stage8_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage11 : signal is "none";
    signal ap_block_pp0_stage11_11001 : BOOLEAN;
    signal out_v_fu_467_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_v_reg_602 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage12_11001 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln134_fu_289_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln139_fu_322_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln140_fu_328_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal step_fu_100 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    signal step_2_fu_257_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_step_1 : STD_LOGIC_VECTOR (29 downto 0);
    signal out_u_fu_438_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage12 : BOOLEAN;
    signal grp_fu_227_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_227_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_block_pp0_stage8 : BOOLEAN;
    signal grp_fu_231_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal zext_ln126_1_fu_247_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln126_fu_267_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln126_fu_263_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln134_fu_283_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal i_fu_299_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln131_fu_303_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln133_fu_312_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal idx1_fu_307_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal idx2_fu_317_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal v_2_fu_334_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_231_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage11 : BOOLEAN;
    signal grp_fu_360_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_fu_370_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln44_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln44_fu_391_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_1_fu_396_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal u_2_fu_365_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_fu_404_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln11_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln11_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_1_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln11_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln11_fu_433_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln16_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln16_fu_454_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln16_fu_459_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_block_pp0_stage8_subdone : BOOLEAN;
    signal ap_block_pp0_stage9_subdone : BOOLEAN;
    signal ap_block_pp0_stage10_subdone : BOOLEAN;
    signal ap_block_pp0_stage11_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ntt_kernel_mul_32ns_32ns_64_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ntt_kernel_mul_32s_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ntt_kernel_add_64ns_64ns_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ntt_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32ns_32ns_64_4_1_U17 : component ntt_kernel_mul_32ns_32ns_64_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_227_p0,
        din1 => grp_fu_227_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_227_p2);

    mul_32s_32s_32_4_1_U18 : component ntt_kernel_mul_32s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_231_p0,
        din1 => q_inv,
        ce => ap_const_logic_1,
        dout => grp_fu_231_p2);

    add_64ns_64ns_64_2_1_U19 : component ntt_kernel_add_64ns_64ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_227_p2,
        din1 => ab_reg_582,
        ce => ap_const_logic_1,
        dout => grp_fu_360_p2);

    flow_control_loop_pipe_sequential_init_U : component ntt_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage12_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    step_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln126_fu_251_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    step_fu_100 <= step_2_fu_257_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    step_fu_100 <= ap_const_lv30_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                ab_reg_582 <= grp_fu_227_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    conv5_i_cast_reg_510(31 downto 0) <= conv5_i_cast_fu_235_p1(31 downto 0);
                icmp_ln126_reg_515 <= icmp_ln126_fu_251_p2;
                j_reg_519 <= j_fu_271_p2;
                lshr_ln131_reg_525 <= lshr_ln131_fu_277_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage12_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then
                out_v_reg_602 <= out_v_fu_467_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ping_addr_1_reg_545 <= zext_ln140_fu_328_p1(12 - 1 downto 0);
                ping_addr_reg_540 <= zext_ln139_fu_322_p1(12 - 1 downto 0);
                pong_addr_1_reg_556 <= zext_ln140_fu_328_p1(12 - 1 downto 0);
                pong_addr_reg_551 <= zext_ln139_fu_322_p1(12 - 1 downto 0);
                twiddle_reg_535 <= local_twiddles_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                u_1_reg_567 <= pong_q1;
                u_reg_562 <= ping_q1;
            end if;
        end if;
    end process;
    conv5_i_cast_reg_510(63 downto 32) <= "00000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage12_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_block_pp0_stage7_subdone, ap_block_pp0_stage8_subdone, ap_block_pp0_stage9_subdone, ap_block_pp0_stage10_subdone, ap_block_pp0_stage11_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when ap_ST_fsm_pp0_stage8 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage8_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                end if;
            when ap_ST_fsm_pp0_stage9 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage9_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                end if;
            when ap_ST_fsm_pp0_stage10 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage10_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                end if;
            when ap_ST_fsm_pp0_stage11 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage11_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage12;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                end if;
            when ap_ST_fsm_pp0_stage12 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage12_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    add_ln133_fu_312_p2 <= std_logic_vector(unsigned(empty_29) + unsigned(trunc_ln131_fu_303_p1));
    add_ln134_fu_283_p2 <= std_logic_vector(unsigned(j_fu_271_p2) + unsigned(empty));
    add_ln16_fu_454_p2 <= std_logic_vector(unsigned(u_2_fu_365_p3) + unsigned(q));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage11 <= ap_CS_fsm(11);
    ap_CS_fsm_pp0_stage12 <= ap_CS_fsm(12);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage8 <= ap_CS_fsm(8);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage10_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage11_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage11_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage12_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage12_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage8_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage8_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage9_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln126_fu_251_p2)
    begin
        if (((icmp_ln126_fu_251_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage12, ap_block_pp0_stage12_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage12_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_step_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, step_fu_100, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_step_1 <= ap_const_lv30_0;
        else 
            ap_sig_allocacmp_step_1 <= step_fu_100;
        end if; 
    end process;

    conv5_i_cast_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv5_i),64));

    grp_fu_227_p0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, zext_ln24_fu_341_p1, zext_ln33_fu_355_p1, ap_CS_fsm_pp0_stage8, ap_block_pp0_stage2, ap_block_pp0_stage8)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
                grp_fu_227_p0 <= zext_ln33_fu_355_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_227_p0 <= zext_ln24_fu_341_p1(32 - 1 downto 0);
            else 
                grp_fu_227_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_227_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_227_p1_assign_proc : process(ap_enable_reg_pp0_iter0, conv5_i_cast_reg_510, ap_CS_fsm_pp0_stage2, zext_ln24_1_fu_346_p1, ap_CS_fsm_pp0_stage8, ap_block_pp0_stage2, ap_block_pp0_stage8)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
                grp_fu_227_p1 <= conv5_i_cast_reg_510(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_227_p1 <= zext_ln24_1_fu_346_p1(32 - 1 downto 0);
            else 
                grp_fu_227_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_227_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_231_p0 <= grp_fu_227_p2(32 - 1 downto 0);
    i_fu_299_p2 <= std_logic_vector(shift_left(unsigned(lshr_ln131_reg_525),to_integer(unsigned('0' & stage_1(31-1 downto 0)))));
    icmp_ln11_1_fu_421_p2 <= "1" when (unsigned(res_fu_404_p2) < unsigned(u_2_fu_365_p3)) else "0";
    icmp_ln11_fu_410_p2 <= "1" when (unsigned(res_fu_404_p2) < unsigned(q)) else "0";
    icmp_ln126_fu_251_p2 <= "1" when (signed(zext_ln126_1_fu_247_p1) < signed(half_n)) else "0";
    icmp_ln16_fu_448_p2 <= "1" when (unsigned(u_2_fu_365_p3) < unsigned(t_1_fu_396_p3)) else "0";
    icmp_ln44_fu_380_p2 <= "1" when (unsigned(t_fu_370_p4) < unsigned(q)) else "0";
    idx1_fu_307_p2 <= std_logic_vector(unsigned(trunc_ln131_fu_303_p1) + unsigned(j_reg_519));
    idx2_fu_317_p2 <= std_logic_vector(unsigned(add_ln133_fu_312_p2) + unsigned(j_reg_519));
    j_fu_271_p2 <= (trunc_ln126_fu_267_p1 and sub53);
    local_twiddles_address0 <= zext_ln134_fu_289_p1(12 - 1 downto 0);

    local_twiddles_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_twiddles_ce0 <= ap_const_logic_1;
        else 
            local_twiddles_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln131_fu_277_p2 <= std_logic_vector(shift_right(unsigned(zext_ln126_fu_263_p1),to_integer(unsigned('0' & stage(31-1 downto 0)))));
    or_ln11_fu_427_p2 <= (xor_ln11_fu_415_p2 or icmp_ln11_1_fu_421_p2);
    out_u_fu_438_p3 <= 
        sub_ln11_fu_433_p2 when (or_ln11_fu_427_p2(0) = '1') else 
        res_fu_404_p2;
    out_v_fu_467_p2 <= std_logic_vector(unsigned(select_ln16_fu_459_p3) - unsigned(t_1_fu_396_p3));
    ping_address0 <= zext_ln140_fu_328_p1(12 - 1 downto 0);

    ping_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage12, ap_CS_fsm_pp0_stage1, ping_addr_reg_540, ping_addr_1_reg_545, ap_block_pp0_stage0, zext_ln139_fu_322_p1, ap_block_pp0_stage1, ap_block_pp0_stage12)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ping_address1 <= ping_addr_1_reg_545;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage12) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then 
            ping_address1 <= ping_addr_reg_540;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ping_address1 <= zext_ln139_fu_322_p1(12 - 1 downto 0);
        else 
            ping_address1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    ping_ce0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ping_ce0 <= ap_const_logic_1;
        else 
            ping_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ping_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage12, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage12_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage12_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            ping_ce1 <= ap_const_logic_1;
        else 
            ping_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    ping_d1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage12, out_v_reg_602, ap_block_pp0_stage0, out_u_fu_438_p3, ap_block_pp0_stage12)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ping_d1 <= out_v_reg_602;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage12) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then 
            ping_d1 <= out_u_fu_438_p3;
        else 
            ping_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ping_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage12, ap_block_pp0_stage0_11001, use_ping_as_input_read_reg_494, icmp_ln126_reg_515, ap_block_pp0_stage12_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage12_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12) and (icmp_ln126_reg_515 = ap_const_lv1_1) and (use_ping_as_input_read_reg_494 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (use_ping_as_input_read_reg_494 = ap_const_lv1_0)))) then 
            ping_we1 <= ap_const_logic_1;
        else 
            ping_we1 <= ap_const_logic_0;
        end if; 
    end process;

    pong_address0 <= zext_ln140_fu_328_p1(12 - 1 downto 0);

    pong_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage12, ap_CS_fsm_pp0_stage1, pong_addr_reg_551, pong_addr_1_reg_556, ap_block_pp0_stage0, zext_ln139_fu_322_p1, ap_block_pp0_stage1, ap_block_pp0_stage12)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pong_address1 <= pong_addr_1_reg_556;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage12) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then 
            pong_address1 <= pong_addr_reg_551;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pong_address1 <= zext_ln139_fu_322_p1(12 - 1 downto 0);
        else 
            pong_address1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    pong_ce0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            pong_ce0 <= ap_const_logic_1;
        else 
            pong_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pong_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage12, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage12_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage12_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            pong_ce1 <= ap_const_logic_1;
        else 
            pong_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    pong_d1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage12, out_v_reg_602, ap_block_pp0_stage0, out_u_fu_438_p3, ap_block_pp0_stage12)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pong_d1 <= out_v_reg_602;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage12) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then 
            pong_d1 <= out_u_fu_438_p3;
        else 
            pong_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    pong_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage12, ap_block_pp0_stage0_11001, use_ping_as_input_read_reg_494, icmp_ln126_reg_515, ap_block_pp0_stage12_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage12_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12) and (icmp_ln126_reg_515 = ap_const_lv1_1) and (use_ping_as_input_read_reg_494 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (use_ping_as_input_read_reg_494 = ap_const_lv1_1)))) then 
            pong_we1 <= ap_const_logic_1;
        else 
            pong_we1 <= ap_const_logic_0;
        end if; 
    end process;

    res_fu_404_p2 <= std_logic_vector(unsigned(t_1_fu_396_p3) + unsigned(u_2_fu_365_p3));
    select_ln16_fu_459_p3 <= 
        add_ln16_fu_454_p2 when (icmp_ln16_fu_448_p2(0) = '1') else 
        u_2_fu_365_p3;
    step_2_fu_257_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_step_1) + unsigned(ap_const_lv30_1));
    sub_ln11_fu_433_p2 <= std_logic_vector(unsigned(res_fu_404_p2) - unsigned(q));
    sub_ln44_fu_391_p2 <= std_logic_vector(unsigned(t_fu_370_p4) - unsigned(q));
    t_1_fu_396_p3 <= 
        sub_ln44_fu_391_p2 when (xor_ln44_fu_385_p2(0) = '1') else 
        t_fu_370_p4;
    t_fu_370_p4 <= grp_fu_360_p2(63 downto 32);
    trunc_ln126_fu_267_p1 <= ap_sig_allocacmp_step_1(12 - 1 downto 0);
    trunc_ln131_fu_303_p1 <= i_fu_299_p2(12 - 1 downto 0);
    u_2_fu_365_p3 <= 
        u_reg_562 when (use_ping_as_input(0) = '1') else 
        u_1_reg_567;
    use_ping_as_input_read_reg_494 <= use_ping_as_input;
    v_2_fu_334_p3 <= 
        ping_q0 when (use_ping_as_input(0) = '1') else 
        pong_q0;
    xor_ln11_fu_415_p2 <= (icmp_ln11_fu_410_p2 xor ap_const_lv1_1);
    xor_ln44_fu_385_p2 <= (icmp_ln44_fu_380_p2 xor ap_const_lv1_1);
    zext_ln126_1_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_step_1),31));
    zext_ln126_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_step_1),32));
    zext_ln134_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln134_fu_283_p2),64));
    zext_ln139_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx1_fu_307_p2),64));
    zext_ln140_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx2_fu_317_p2),64));
    zext_ln24_1_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(twiddle_reg_535),64));
    zext_ln24_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(v_2_fu_334_p3),64));
    zext_ln33_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_231_p2),64));
end behav;
